Testing/Functional/RegoCachedProviderTesting.ps1

RegoCachedProviderTesting does not set location as expected when user has multiple instances of SCuBAGear.
The directory search function in line 58 was removed as it does not behave as expected when the user has multiple instances of SCuBAGear on their device. The set location was changed to only move up on folder with Split-Path to be in the correct file path for Invoke-SCuBA & still in the same instance.
Closing #106 
- `.\RunFunctionalTests.ps1 -p aad`
- Run above command when multiple instances of SCuBAGear & only 1 instance exists on device

Bug Fix: RegoCachedProviderTesting.ps1 file paths

---

Rego/OneDriveConfig.rego
Testing/Unit/Rego/OneDrive/OneDriveConfig2_03_test.rego

Removed checks for DefaultLinkPermission
Add check for DefaultSharingLinkType; FileAnonymousLinkType; FolderAnonymousLinkType to policy 2.3 
Adjusted the unit test cases
Reports now gives detailed description when requirement is not met
OneDrive 2.3 policy
edited the policy to check user permission for view and edit for OneDrive
adjusted the unit test cases
closes #98 
1. Open the Sharepoint Admin Center
2. Navigate to Policies > Sharing
3. Set the External Sharing slider to Anyone (Need do it on Sharepoint first then OneDrive)
4. Scroll to the section "Choose expiration and permissions options for Anyone links."
5. Set the Files permission to View and Edit
6. Set the Folders permission to View, edit and upload
7. Run the tool
The result should reflect that both 2.1 and 2.3 did not meet …

Updated OneDrive 2.3 policy 

---

.github/workflows/run_release.yaml

* Adds a github action that will create draft releases artifacts in zip format with signed powershell code
* Can be extended in future with other steps (testing, packaging, etc) and refined as appropriate
* Uses draft releases so that release notes can be manually refined as necessary.
This closes issue #95.  It enables us to release signed code that will run on windows without unblock-file. 
Initial testing was completed in a forked branch with an untrusted CA.   PR has been tested by running action from dev branch using real certificate.  Release artifacts run successfully without unblock-file in an environment that enforces signing for MOTW scripts.

Implement code signing and basic pipeline to create draft releases.

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1

Explicitly set encoding to UTF8 when Set-Content is invoked.
This standardizes encoding for files written to the file system. Primarily this is to ensure the OPA Agent is getting 
files encoded as UTF8. Closes issue [#20](https://github.com/cisagov/ScubaGear/issues/20)
Executed 'Invoke-SCuBA -ProductNames aad' in both PowerShell 5.1.19041.2364 and 7.3.0.  Verified ProviderSettingExport.json was utf8 encoded. 
- [x ] This PR has an informative and human-readable title.
- [x ] Changes are limited to a single goal - *eschew scope creep!*
- [x ] *All* future TODOs are captured in issues, which are referenced
- [x ] All relevant type-of-change labels have been added.
- [x ] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x ] These code changes …

Set encoding explictly

---

Rego/DefenderConfig.rego
Testing/Unit/Rego/Defender/DefenderConfig2_02_test.rego

#Fix Defender 2.2 Policy 3 bug when DLP policy in test mode#
- Adds a new test for Defender 2.2 policy item 3 to include rules when the enclosing policy is set to test mode even if the rule itself is set to block
- Updates wording in the report details to note that it may be the policy, not the rule, causing the warning
- Adds a new unit test to validate the new use case is captured
Closes #42
Defender baseline 2.2 policy 3 states that:
* The action for the DLP policy SHOULD be set to block sharing sensitive information with everyone when DLP conditions are met.
The assessment report, however, was reporting PASS for some rules even though the associated policy does not enforce the block when set in Test mode rather than On.  This is inconsistent with the intent of the baseline policy to …

Fix Defender 2.2 Policy 3 bug when DLP policy in test mode

---

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1

- Updated `Get-EXOTenantDetail` to omit the "EXOAdditionalData" values returned from `Get-OrganizationConfig`
- Updated the Get-OrganizationConfig cmdlet call used in the EXO Provider to select only the fields we need for EXO 2.13
- Both changes above remove the offending duplicate key `RootPublicFolderMailbox.Type` field generated from ConvertTo-Json.
Closes #132
TODO: address the root cause in the pull request that solves issue #139 
- Confirmed on main branch that Test Tenant 1 (G5), Test Tenant 2 (G3), and now even Test Tenant 4 (E5) are erroring when running `Invoke-Scuba -ProductNames exo` 
- Ran the updated code in this branch against Test Tenant 1 (G5) with no issues to EXO 2.13 and other providers with the following commands. `Invoke-Scuba -ProductNames exo` `Invoke-Scuba …

Hotfix the fatal error caused by duplicate JSON keys being generated in the EXO Provider

---

Rego/EXOConfig.rego
Testing/Unit/Rego/EXO/EXOConfig2_07_test.rego

- Adds extra line in EXO 2.7 rego that filters the rules analyzed in the code by whether the rules are enabled. 
- Writes unit testing for EXO 2.7 to accommodate for the new logic. 
- Before this pull request, EXO 2.7 will pass if the rule is correctly configured but disabled, defeating the purpose of the baseline control. The solution is to add a line of rego code before checking the rule to see if it is correctly configured that filters the rules down to only the enabled rules.
- This pull request closes issues 126 and 27. 
- I tested my changes on a test tenant by creating two rules: a correctly configured rule and an incorrectly configured rule. After making the change in the rego code, I confirmed that when the correctly configured rule is enabled that the test passes. I also tested …

EXO 2.7 Rego Bug Fix | Only Enabled Correctly Configured Rules Pass

---

PowerShell/ScubaGear/Modules/Connection/ConnectHelpers.psm1
PowerShell/ScubaGear/Modules/Connection/Connection.psm1
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportOneDriveProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
PowerShell/ScubaGear/RequiredVersions.ps1
Rego/OneDriveConfig.rego
Rego/SharepointConfig.rego
Testing/Unit/Rego/OneDrive/OneDriveConfig2_01_test.rego

- Add Service Principal Authentication via CertficateThumbprint, AppID, and Organization (domain name).
- Set up `Connection.psm1` for other Service Principal authentication methods to be added in the future.
- Raise minimum versions for EXO and Teams PowerShell modules.
- Add PnP.PowerShell module dependency for Service Principal Authentication support for SPO and OneDrive.
- Handle OneDrive 2.1 which does not have the field we need to check when using PnP.PowerShell.
- Correct erroneous Defender GCCHigh and DOD endpoints.
- Speed up Graph Beta Profile selection for AAD.
Closes #96
Closes #63
Closes #144
Future TODO: add other Service Principal Authentication methods.
Future TODO: create a function to register an Azure AD Application with the permissions needed.
- Ran the updated code in …

Add Service Principal authentication via CertificateThumprint parameters and correct erroneous GCC High/DOD Defender endpoints

---

.github/workflows/run_opa_tests.yaml
PowerShell/ScubaGear/Dependencies.ps1
PowerShell/ScubaGear/RequiredVersions.ps1
SetUp.ps1

- Changes `SetUp.ps1` to add `-MaximumVersion` parameter to `Install-Module` calls. 
`Install-Module -MaximumVersion {Maximum version listed in RequiredVersions.ps1}`
- Additional text to `Write-Information` calls to reflect the changes made above.
- Updates MicrosoftTeams PowerShell module Maximum version to `5.99.99999`
Closes #176 
- Tested on Test Tenant 1 (G5), Test Tenant 2 (G3), Test Tenant 4 (E5), and Test Tenant 6 (GCC High) for regressions. None found.
- Tested new `SetUp.ps1` changes on 2 different client machines. When limited to MicrosoftTeams `MaximumVersion = 4.99...` `MicrosoftTeams 4.9.3` was installed successfully and `Invoke-SCuBA` ran smoothly. After updating the MicrosoftTeams PowerShell `MaximumVersion = 5.99...`,   `MicrosoftTeams 5.0` was installed successfully and …

Constrict SetUp.ps1 to install maximum acceptable version

---

.github/workflows/run_release.yaml

Placed release into root folder with version in zip file 
Adhere to standard release practices.
Manually triggered Build & Release action on branch to actuate a release.  
Verified release zip content is under root folder

Scuba release should be in root folder

---

Rego/EXOConfig.rego
Testing/Unit/Rego/EXO/EXOConfig2_03_test.rego
Testing/Unit/Rego/EXO/EXOConfig2_04_test.rego

Adjusted the Rego tests for EXO 2.3 and 2.4 so that the DNS answers are expected as a list, rather than a single string.
Closes #214.
Tested on both G5 and E5 tenants. Manually inspected results for correctness as well as compared results with v0.2.0.

Fix bug with DKIM and DMARC

---

PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
Testing/Unit/PowerShell/Providers/PowerPlatformProvider/Export-PowerPlatformProvider.Tests.ps1

Fixes a bug where non-NA tenants would be unable to run Power Platform because an error would be thrown. 
This bug was added in because of a check that was added in #114 to determine if the user passed in the correct `$M365Environment` variable.
Closes #201 
Tested against the E5/G5 and GCC tenants.
Added unit test for testing Non-NA regions

Support non-NA regions when running Power Platform

---

baselines/defender.md

This change updates the Defender secure configuration baseline markdown document, specifically MS.DEFENDER.4.2v1, to include SharePoint sites in custom DLP policies.
Ensures proper coverage of DLP actions across different M365 services by adding SharePoint sites to the set of services scanned for sensitive information by the custom policy. 
closes #278
Follow the implementation guidance for MS.DEFENDER.4.2v1 to create a custom policy that includes the SharePoint sites location.  This was tested in the G5 test tenant to confirm the setting works as intended.

Update DLP Custom Policy locations

---

Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1
Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1

Smoke test was not handling Conditional Access Policy table properly (treated as Policy Group Table) and automatically showing report.   
closes #417 
Properly handle CAP table to not report incorrect error. 
Use new -Quiet switch in Invoke-Scuba to make report quiet. 
Execute Smoke test.  Verify only 'real' missing policies reported. Where missing means exists in Secure Baseline but has no rego implementation. 
Use appropriate credentials and tenant 
```console
$TestContainers = @()
$TestContainers += New-PesterContainer -Path "Testing/Functional/SmokeTest/SmokeTest001.Tests.ps1" -Data @{ Thumbprint = "04C04809CC43AF66D805399D09B69069041574B0"; Organization = "y2zj1.onmicrosoft.com"; AppId = "9947b06c-46a9-4ff2-80c8-27261e58868a"; M365Environment = "commercial" }
$TestContainers += …
```

Update Smoke Test to handle CAP 

---

Rego/AADConfig.rego
Testing/Unit/Rego/AAD/AADConfig_07_test.rego

Update MS.AAD.7.6v1 rego to only apply to global admin per recent baseline change.
Closes #415. 
- Tested on G5 tenant. Passes as expected.
- Tested on E5 tenant. Toggled the feature, passes and fails as appropriate.
- Tested on G3 tenant. Failed and displays the license warning as expected.
- Tested on GCC high tenant. Toggled the feature, passes and fails as appropriate.
NOTE: some teams Rego unit tests will fail until https://github.com/cisagov/ScubaGear/pull/426 is merged in. Failure is unrelated to changes made in this branch.

Update MS.AAD.7.6v1 rego to only apply to global admin 

---

PowerShell/ScubaGear/RequiredVersions.ps1
Rego/AADConfig.rego
Rego/Utils/PolicyUtils.rego
Rego/Utils/TestUtils.rego
Testing/Unit/Rego/AAD/AADConfig_03_test.rego

Verify a CAP exists for acceptable MFA Strengths applied to All users/app with only explicilty specified exclusions 
closes #351  - Will not auto close since [not default branch](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)?
Initial implementation of new policy
Added new unit test for policy. All pass.
Tested against tenants and got expected results. 
NOTE: Use caution if attempting to set conditions to pass policy in tenant because you can lock out users. 

Implement MS.AAD.3.1v1 phishing resistant mfa for all users

---

Testing/RunUnitTests.ps1

Updated RunUnitTest script that were broken by updated baselines.
Due to the change of baseline names, the PowerShell script was unable to properly run to test each individual unit test. There was also an issue where test names within each control group that did not exist but were specified with the -t option would pass. This was resolved where a warning would appear if a test name did not exist. 
I tested the changes made by testing each product individually as well as calling individual baseline test numbers to ensure that the script is supposed to run as intended. I also tested if a specific baseline that was specified did not exist as well as if a test within the specific baseline did not exist. 
Others can test by running: `ScubaGear\Testing\RunUnitTests.ps1 -p <product name(s)> -b …

Update unit test script

---

baselines/powerbi.md

Changed formatting and content of PowerBI baseline to match new formatting structure
Consolidated format and clearer to read and understand layout
N/A

Adjudicate substantive changes to the powerbi baseline markdown following the new format

---

baselines/exo.md

- Reformatted the baseline document with new structure and policy identifiers
- Refine and update policy statements to address pilot feedback. 
- Updated implementation steps for any out-of-date instructions
- Address the EXO baseline portion of #29 . Code updates need to be made in defender.
Added to this PR from the TODOs.
- address mirrored Defender policies. #435 
- address Purview Audit name change #277
TODO: address code updates in #429 
TODO: add rationale to the baseline document Issue: #434 PR: #447
[Looks like closing keywords no longer work if the base branch isn't the default branch?](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
closes #285 
closes #247
- Retested instructions for the EXO policies on commercial and GCC …

Address EXO comment and structural changes in the baseline document

---

baselines/aad.md

This PR is designed to facilitate a formal review of the revised AAD baseline from CISA Scuba principals and the Scuba development team. Following this review the AAD baseline should be in a state for sending to the CISA agency formal review process.
We have active development issues against this baseline at the moment, including new policy implementations and tweaks to existing policies. If any changes occur during this baseline review which materially affect the ScubaGear code, it may require a notification to the affected developers.

formal internal review of AAD baseline

---

Rego/AADConfig.rego
Testing/Unit/Rego/AAD/AADConfig_03_test.rego

Check Authentication Strength for Phishing Resistance MFA.
Make both MS.AAD.3.2v1 and MS.AAD.3.6v1 depend/use MS.AAD.3.1.1v1 Authentication Strength checks.  
closes #409 
closes #413
Phisting resistant MFA is required in new secure baseline for MS.AAD.3.2v1 and MS.AAD.3.6v1
Added additional unit tests for MS.AAD.3.2v1 and MS.AAD.3.6v1.  
Ran InvokeScuba against all tenants. 

Update MS.AAD.3.2v1 & MS.AAD.3.6v1 to Check Authentication Strength for Phishing Resistance MFA

---

Rego/DefenderConfig.rego
Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego
sample-config-files/defender-config.yaml

Update MS.DEFENDER.1.5v1 rego policy to validate that the existing tenant Defender for Office365 strict preset security policy configuration includes the sensitive accounts filter expressions specified in the configuration file provided via the `-ConfigFilePath` parameter to `Invoke-Scuba` OR that the Defender for Office365 protections are enabled for all recipients.
This change is required as the old check only made sure that a custom policy for Defender for Office365 was present.  The baseline updates and ability to specify sensitive accounts via a configuration file allows for a more accurate assessment and the check needs to be changed to match the updated baseline policy.
Closes #487 
Run unit tests to validate changes pass. `cd  Testing; .\runUnitTests.ps1 -p defender`
Change can be …

Update MS.DEFENDER.1.5v1 ATP rules check for sensitive users

---

Rego/DefenderConfig.rego
Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
sample-config-files/defender-config.yaml

The previous policy only checked that impersonation protection was enabled.  The assessment did not ensure that agency domains were included in the protection specifications.  The new rego assessment uses the `-ConfigFilePath` setting to allow users to specify the agency domains that should be included in both the standard and strict preset security policy impersonation protection configuration. 
The update also includes an expanded sample `defender-config.yaml` file that shows annotated examples of each configuration setting.
Defender 2.2 specifies that agency domains should be added to the strict and standard preset policy for impersonation protection settings. By allowing the users to specify these in the config file, we can verify the correct domains are added and all tenant users are …

Update MS.DEFENDER.2.2v1 to assess agency domains in impersonation protection

---

Rego/TeamsConfig.rego
Testing/Unit/Rego/Teams/TeamsConfig_05-test.rego

Currently the code shows the opposite result of what we want. 
Modified rego and unit test so that MS.TEAMS.5.1v1, MS.TEAMS.5.2v1, MS.TEAMS.5.3v1 
- passes when the Global is set to "Block all" or "Allow specific apps"
- fails when the Global is set to "Allow all" or "Block specific apps"
closes #506 
closes #483 
Test all four cases "Block all", "Allow specific apps", "Allow all" and "Block specific apps" to make sure it works properly. 

MS.TEAMS.5.* hotfix

---

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Rego/EXOConfig.rego
Rego/Utils/ReportUtils.rego
Testing/Unit/Rego/EXO/EXOConfig_01_test.rego
Testing/Unit/Rego/EXO/EXOConfig_02_test.rego
Testing/Unit/Rego/EXO/EXOConfig_03_test.rego
Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
Testing/Unit/Rego/EXO/EXOConfig_05_test.rego
Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
Testing/Unit/Rego/EXO/EXOConfig_07_test.rego
Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
Testing/Unit/Rego/EXO/EXOConfig_10_test.rego
Testing/Unit/Rego/EXO/EXOConfig_11_test.rego
Testing/Unit/Rego/EXO/EXOConfig_12_test.rego
Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
Testing/Unit/Rego/EXO/EXOConfig_15_test.rego
Testing/Unit/Rego/EXO/EXOConfig_16_test.rego
Testing/Unit/Rego/EXO/EXOConfig_17_test.rego
baselines/exo.md

- Updates all Provider/Rego code to align to the revised EXO baseline
- Improvements to the accuracy of the Rego check for Policy Group 6 and 12. 
- Does not address #526 where text in the requirements can look barbaric.
Closes #429 
Additionally Resolves #562, #563, #564, #560, #571 
Addresses the EXO half of #124. Teams half still needs to be addressed.
Tested on E5, G3, G5, GCC High Tenants.

Update EXO code to align to revised emerald baseline 

---

Rego/DefenderConfig.rego
Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego

Updates in this pull request align the old Defender Data Loss Prevention (DLP) assessment code with the new baseline version policies and ensures the new assessment only produces a single test result for each policy statement rather than multiple results per statement.  These updates include:
- Merged results for MS.DEFENDER.4.1v1 to ensure minimum sensitive info types are included in the DLP custom policy
- Merged results for MS.DEFENDER4.2v1 that checks that custom policy includes desired locations
- Adding support to MS.DEFENDER4.2v1 to check that the Device location is included as per policy update
- Adding initial support for detection of sensitive info types in advanced DLP rules in policies
Note: Full support for advanced rules is beyond scope of this PR and captures as TODO in …

Update MS.DEFENDER.4.1 and MS.DEFENDER.4.2 assessment checks

---

baselines/defender.md

Upon review of the Defender Rego code I discovered that a few of the policies 1.1, 1.3 and 1.5 rely on the Get-ATPProtectionPolicyRule cmdlet which requires the Defender for Office Plan 1 license. This needs to be reflected in the baseline license requirements section.
Change required to reflect the dependency of the Get-ATPProtectionPolicyRule cmdlet required for section one policies in the baseline.
Closes #598
N/A

Update defender baseline to include missing license requirement for section 1

---

PowerShell/ScubaGear/Modules/Connection/Connection.psm1
README.md

This PR simply updates service principal permissions documentation in the README after doing some extensive testing. 
A few surprises for 2 of the products. Notes below. 
- These Graph API Permissions are not needed by PnP PowerShell. Unsure why they are listed in this [documentation](https://microsoft365dsc.com/resources/sharepoint/SPOSite/#application-permissions). Removed them from our list of needed SP permissions.
- `Application.Read.All`
- `Domain.ReadAll`
- SharePoint needs both the `Sites.FullControl.All` SharePoint API permission AND the `Global Reader`  or `Directory.Read.All`  to function. 
- This is because `Get-MgBetaOrganization` which is used for SharePoint authentication requires either the `Global Reader` role or the `Directory.Read.All` API permission to execute.
- …

Update Service Principal documentation in the README

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Rego/Utils/ReportUtils.rego

This request updates both the Rego report utility `ScubaBaseURL` variable and PowerShell HTML report variable `MarkdownLink` in `CreateReport.psm1` to generate versioned URLs to GitHub using the 'v' prefix in front of the release version of the tool.
Without this fix and with the existing build and sign release action, ScubaGear version tags include the 'v' prefix.  However, URLs in Rego and the HTML report are built without the prefix.  As a result, URLs will be broken and incorrect and users will not be directed to the correct website location for baseline references in test results and reports.
Closes #650 
Ran `Invoke-Scuba -p *` to generate a full set of reports and validated that URL references to the baselines in report details contains the proper 'v' prefix.
Generated HTML report …

Fix versioned tag in URLs

---

.regal/config.yaml
CONTENTSTYLEGUIDE.md

Update rules to be warning instead of ignore
1. line length
2. identically named tests
3. constant condition* (see the original comment chain for more context)
4. test-outside-test-package
5. prefer-some-in-iteration
6. rule-length
This issue is to address follow ups from #594 along with any other Linter rules we wish to follow. 
Closing #615 
The linter WILL display warnings, they will be fixed in the related refactor issues, see #638 

Address Rego Linter (Regal) Rules

---

Rego/DefenderConfig.rego
Rego/EXOConfig.rego
Rego/PowerPlatformConfig.rego
Rego/TeamsConfig.rego
Rego/Utils/ReportUtils.rego

Rego compilation errors were being thrown due to unused function parameters. For each instance parameters were changed to the wildcard variable "_".
Resolves issue #195, OPA versions 0.50+ introduce updates to strict mode checking for unused variables. For newer versions of OPA, ScubaGear's automated checks will fail preventing merges into main from happening. 
Although this PR addresses the strict mode errors in Rego policies, it does not address the OPA executable version downloaded in `OPA.ps1` or the version specified in Run OPA tests workflow, #593.
To test these changes: 
1. Go to OPA documentation, select the version you want to test, then download the executable
2. Run the OPA strict mode check 
```
.\opa_windows_amd64.exe check Rego Testing\Unit\Rego --strict
```
3. Repeat steps …

Update unused function parameters with wildcard variables

---

.github/workflows/run_powershell_tests.yaml
PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
Testing/Unit/PowerShell/Connection/Connect-DefenderHelper.Tests.ps1
Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1

Wrapped call to opa executable with function s it can be mocked in unit test.  
closes #245 
Unit test code is white box testing and should not depend on external services.  This allows us to test w/o OPA present.
1. PowerShell Unit test passes
2. Invoke Scuba execute properly
3. Workflow run_powershell_test passes

Breaking dependency on opa in unit testing

---

OPA.ps1

This update adds progress bar to download OPA
An enhancement to the current OPA.ps1 as well as Setup.ps1
closes #197 
Run OPA.ps1  and/or Setup.ps1 and check if there is an download progress bar
-->

add progress bar for OPA download

---

Rego/EXOConfig.rego
Testing/Unit/Rego/EXO/EXOConfig_01_test.rego
Testing/Unit/Rego/EXO/EXOConfig_02_test.rego
Testing/Unit/Rego/EXO/EXOConfig_03_test.rego
Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
Testing/Unit/Rego/EXO/EXOConfig_05_test.rego
Testing/Unit/Rego/EXO/EXOConfig_06_test.rego
Testing/Unit/Rego/EXO/EXOConfig_07_test.rego
Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
Testing/Unit/Rego/EXO/EXOConfig_10_test.rego
Testing/Unit/Rego/EXO/EXOConfig_11_test.rego
Testing/Unit/Rego/EXO/EXOConfig_12_test.rego
Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
Testing/Unit/Rego/EXO/EXOConfig_15_test.rego
Testing/Unit/Rego/EXO/EXOConfig_16_test.rego
Testing/Unit/Rego/EXO/EXOConfig_17_test.rego

Refactor Exo Rego Code

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1

Invoke-RunCached broken due to change of location of Rego folder
Closes #784 
Import-Module .\PowerShell\ScubaGear
Invoke-RunCached -p teams 
- [] Revert dependencies to default branches.
- [] Finalize version.

Quick Fix of Invoke-RunCached

---

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/AAD.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_06_test.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml

- Import AAD settings from Get-MgBetaDomain in `ExportAADProvider.psm1`, 
- Write unit tests to indicate correct and incorrect values in `AADConfig_06_test.rego`, write functional tests in `aad.testplan.yaml`
- Implement MS.AAD.6.1v1 policy in `AADconfig.rego`.
MS.AAD.6.1v1 was marked as not implementable, but it can now be checked with `Get-MgDomain`.
This resolves #398 
From the Testing directory, run `.\RunUnitTests.ps1 -p aad -c 6`
To run functional tests, setup $TestContainers array, setup $PesterConfig to filter based on MS.AAD.6.1v1 tag, then run the following: 
`$Config = New-PesterConfiguration -Hashtable $PesterConfig`
`Invoke-Pester -Configuration $Config`
Run the tool against commercial, gcc, and gcchigh environments 

Implement MS.AAD.6.1v1 check user password expiration 

---

.github/workflows/run_linter_powershell.yaml
.github/workflows/run_markdown_check.yaml
Testing/Functional/Products/TestPlans/aad.testplan.yaml
Testing/Linting/MegaLinter/.powershell-psscriptanalyzer.psd1
sample-config-files/aad-config.yaml

The updates in this PR resolve several warnings from existing linting checks which includes:
* Adding a PSScriptAnalyzer configuration file to suppress some warnings during checks
* Updating the PowerShell linter workflow to use the new configuration settings
* Resolving YAML trailing whitespace and indentation warnings
* Fixes path to Pester tests for markdown checks workflow
This change resolves automated testing check failures.  Resolving the issue ensures a clean passing baseline for the current development branch.
Closes #808
Since these updates affect the automated checks.  Testing is done by reviewing the `Lint Check for YAML` and `Lint Check for PowerShell` check results.  Also added changes to fix silent fail of 'Markdown Check' workflow. Results should be green and show that all …

Fix YAML and PowerShell linter warnings

---

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
PowerShell/ScubaGear/Rego/EXOConfig.rego

- Adjust DNS query logic so that a retry over DoH is not triggered by NXDOMAIN.
- Make EXO PowerShell compliant with the new linter
Closes #764. Aims to reduce warning fatigue.
- Ran against the regular testing tenant, all results are correct
- Ran the `Invoke-RobustDnsTxt` function in one of the pilot environments that has the empty DNS response issue. Retries over DoH still occurred as designed.

Remove DoH Retry for NXDOMAIN

---

PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
Testing/Functional/Products/Products.Tests.ps1

Updating the test orchestrator to support multiple possible custom implementation reporting strings.
The EXO tests related to Custom Implementation where the isCustomImplementation is set to true fails because the ReportDetail string associated with custom implementations for EXO were updated in the emerald release to provide a more descriptive response about possible custom implementations. Since the test orchestrator uses a single string match, EXO custom implementation tests fail. Updating the test orchestrator custom implementation string match to the new EXO ReportDetail string shows the test pass properly.
closing #619 
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to rebase from the …

Updating the test orchestrator for custom implementation reporting strings

---

PowerShell/ScubaGear/Modules/Connection/Connection.psm1
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
README.md

This pull request modifies the AAD provider's Get-PrivilegedUser function to support getting user to PIM Group eligible assignments which is a current gap in our code. The PR also addresses a longstanding bug where users would sometimes get a duplicate role in their privileged_users node in the JSON. I also changed the connection module to request the required MS Graph permission scope since we are introducing a new cmdlet and I added the permission to the respective sections in the README file.
Closes #757
Closes #703
I tested this by creating test users and groups in all the test tenants that support PIM to ensure that the AAD code picks up the users that are assigned to a PIM group as Eligible. No updates were necessary to the functional tests because nothing changed in the JSON …

Add PIM for groups support to AAD provider

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportTeamsProvider.psm1

This PR makes it so that ScubaGear no longer attempts to remove all backslashes, only the specific character sequences known to cause problems for Rego.
The provider output can include characters that Rego attempts to interpret as escape sequences (such as `\/`, which is output when you convert a date to json in PowerShell 5 (e.g., `Get-Date | Convert-ToJson`). These sequences result in the error "unable to parse input: yaml: line x: found unknown escape character." Previously, ScubaGear attempted to circumvent this issue by wholesale removing all backslashes from the resulting json. However, there are cases where that technique resulted in broken json (see #807 and #770). 
Closes #818.
Tested on the E5, G3, G5, and GCCHigh tenants, asserting that the number of tests passing/failing …

Refactor escape sequence handling

---

PowerShell/ScubaGear/Modules/Connection/Connection.psm1

Quick one liner change to disable the PnP PowerShell update banner. 
Done by setting the PnP update banner environment variable to false.
Closes #766 
Tested on the various test tenants. The PnP banner will no longer appear when running Invoke-SCuBA -ProductNames 'sharepoint' while authenticating via Service Principal. 
```
Invoke-SCuBA -ProductNames 'sharepoint' -CertificateThumbprint "<insert-thumbprint>" -AppID "<insert-appid>" -Organization tenant.onmicrosoft.com`
```
Unfortunately, the Power Platform warning messages still appear when running the conformance check on Power Platform. 
There doesn't seem to be a fix for that on our end. 
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-request) reference to …

Disable PnP PowerShell update banner

---

Testing/Functional/Products/TestPlans/teams.testplan.yaml

During nightly product functional testing, a few issues were found against some test cases - all these issues are while setting a config parameter. The attempted settings were either not allowed because of the config elements are not-editable or because the current tenant state does not allow the attempted config. 
This pull request updates the Teams test plan to fix the above issues. The Teams test cases 1.1, 1.2 and 1.5 were earlier attempting to edit Microsoft supplied non-custom meeting policies. But since these meeting policies were not editable - the test was failing with 'setting not possible' exception. Note that these meeting policies are redundant (Microsoft discontinued them and made them not assignable) and are expected to be deprecated soon. Test plan is fixed by filtering …

Update test plan for Teams product to fix issues observed during Nightly-Products-Functional-Test workflow

---

PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config1.json
PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/config_test_load_config2.json

This PR fixes #844, in which calling `.LoadConfig` more than once has no effect. The fix is trivial and just invokes `.ResetInstance` before loading a new file.
Primarily needed to avoid surprises during testing.
Also closes #845, added a comment-based help docstring to ScubaConfig, per discussion with team; simply easier to do that one here as well.
Added a unit test almost identical to the diagnostic test outlined in #844 

Fixes ScubaConfig.LoadConfig repeated invocations

---

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/ProviderSettingsExport.json
PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-AADProvider.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
PowerShell/ScubaGear/baselines/aad.md
Testing/Functional/Products/TestPlans/aad.testplan.yaml

For Rego policy check 5.3 we can replace Get-MgBetaPolicyAdminConsentRequestPolicy and use Get-MgBetaDirectorySetting instead. We already use Get-MgBetaDirectorySetting for policy 5.4 so we can remove the extra cmdlet Get-MgBetaPolicyAdminConsentRequestPolicy from the provider to make AAD run faster.
When developing the functional test cases for AAD I discovered that the Get-MgBetaDirectorySetting returns a field named EnableAdminConsentRequests that we can check to see if the admin consent workflow is enabled.
Increase performance of ScubaGear
closes #729 
- Ran UT, passed
- Ran FT for AAD, passed
- Ran Invoke-Scuba against tenant and got expected results. 
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebase-and-update-a-pull-reque …

Remove an unnecessary cmdlet from aad policy check 5.3 to improve performance of the provider

---

PowerShell/ScubaGear/RequiredVersions.ps1

The current ScubaGear depends on a number of Microsoft PowerShell modules to interact with M365 services.  Previously, ScubaGear setup installed the latest version of these libraries available in PSGallery.  This update sets the maximum version for the Microsoft.Graph.* modules to v2.12.0 and the Microsoft.Online.SharePoint.PowerShell to v16.0.24322.1200 so that newer versions will not be installed.
This change is needed due to errors in the upstream modules that causes ScubaGear to fail.  The solution chosen was to "pin" the module versions used to the last working versions until the upstream modules have been fixed to prevent ScubaGear users from receiving these errors.
Closes #889 
Closes #903 
Closes #904 
Changes were tested by verifying failures after removing all Microsoft modules …

Add MSGraph and SPO library max versions

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml

This pull request modifies the AAD Rego code for policy MS.AAD.7.2 "Privileged users SHALL be provisioned with finer-grained roles instead of Global Administrator." by implementing a custom calculation for computing the tenant's least privilege check.  The least privilege score is calculated as the ratio of the number of users with Global Admin privileges to the number of users with other highly privileged roles. This change allows ScubaGear to automatically check for the least privilege score versus having the user manually check the Secure Score value for the action named **Use least privileged administrative roles**. This PR also includes Rego unit tests to check the logic in the Rego code.
Closes #760 
I tested this against the G5 and E5 tenants which each had different scores. In …

Add Least Privilege Score Check to Policy MS.AAD.7.2v1

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1

This closes the PR where there is a repeating # which causes links in the report to take you to the top of the page rather than the correct location.
Closes #897 
Removed a duplicate # which was causing the links to the top of the page rather than directly to the appropriate control group as intended. This is a small change with only one line of code changed within the createreport file.
This was tested on the different tenants, ensuring that the links were correctly working and taking the user to the correct subsection of the website rather than the top of the website.

Fixes Broken Links in Baseline Report

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/CreateReport/scripts/ParentReport.js
PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
PowerShell/ScubaGear/Modules/CreateReport/scripts/utils.js
Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1

- Adds a new function in utils.js of ScubaGear's CreateReport module. The function applies scope="col"/"row" to each \<table> in both parent and individual HTML reports.
- Slightly modify CAP table to contain a \<tbody> tag so the new function operates correctly. 
- In CreateReport.psm1, fragments for the policy control tables are modified with an id, e.g. AAD-1, for better error handling. 
- Modify SmokeTest002.Tests.ps1 to check if attributes are set correctly
Resolves #93 
The change is required for 508/WCAG conformance, primarily under [Guideline 1.3.1](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html).
A technique sufficient for meeting this guideline is [Technique H63](https://www.w3.org/WAI/WCAG21/Techniques/html/H63), Using the scope attribute to associate …

Add scope attributes to tables in HTML Report

---

PowerShell/ScubaGear/Modules/Connection/Connection.psm1
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
README.md
Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml

Updated AAD Provider to add PIM configurations to the JSON for groups that are enrolled in PIM for Groups in the Get-PrivilegedRole function. Modified the Rego to support reporting on PIM group configurations in addition to role configurations. This affects AAD policies 7.6 - 7.9. 
closes #919 
closes #981 
closes #975 
closes #944 
Salient items changed:
- Added code to the AAD provider Get-PrivilegedRole to support PIM for groups
- Modified Rego policies to report on roles and PIM groups
- Added required permissions to the Connection object
- Modified existing functional tests for 7.6 through 7.9 and added new tests for PIM for groups scenarios
PIM Groups provide mechanism to give users privileged access.  This enhancement allows to make sure notifications/alerts are produced …

Add code to AAD provider and REGO for 7.6 through 7.9 to support PIM for Groups

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/ProviderSettingsExport.json
Testing/Functional/Products/Products.Tests.ps1
Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1

This PR concludes adding licensing information to ScubaGear.
The licensing information has been added to the bottom part of the AAD report for users to be able to review. This will conclude the larger epic for adding licensing information to ScubaGear (#466)
Closes #778
This was tested using the different tenants and checking to make sure that the report will still generate without issues even if the AAD report isn't run.

(New) Add Licensing Information to AAD Report

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Merge-JsonOutput.Tests.ps1

- Had a request to add this timestamp into the JSON.
- PR Just adds a ISO 8601 compliant timestamp to the Provider JSON.
Closes #1002 
Just run ScubaGear normally and check if the `timestamp` key is within the JSON.
Compatible with all tenants of course. 
- ~All automated checks (e.g., linting, static analysis, unit/smoke tests) passed.~
Smoke test tests are failing due to expired licenses. 

Add a UTC timestamp to the Provider JSON

---

.github/workflows/run_module_version_bump.yml

- This PR adds a GitHub action for bumping the ScubaGear version in the manifest and the README and automatically create a PR. 
- The workflow has one input the module version we want to bump to. For example if we want ScubaGear to be version `1.2.0`. Then the input will be `1.2.0`. No `v`'s needed. 
- This PR is one of a series of dependency updates that are incoming. 
Closes #986 
Example PR that's created running the workflow [example PR](https://github.com/buidav/ScubaGear/pull/19).
You can also fork ScubaGear, specifically this branch, to test this PR or your own fork.
Note that this GitHub action requires write permissions to PRs.
You can configure the permissions for this on the repo settings under `Settings` => `Actions` => `General` => `Workflow permissions`. Ensure the options …

Create a workflow for bumping the ScubaGear module version

---

Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MatchedRecipientDomain.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedGroup.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedRecipientDomain.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.4v1/MismatchedUser.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MatchedRecipientDomain.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.1.5v1/MismatchedRecipientDomain.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedUser.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MatchedWithMixedCase.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.1v1/MismatchedUser.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.2v1/AgencyDomainList.yaml
Testing/Functional/Products/TestConfigurations/defender/MS.DEFENDER.2.3v1/PartnerDomainList.yaml

Remove default variables from Defender test configs.  In particular, the `OPAPath` variable is set to the old `.` default which causes testing to fail if the tester does not have the OPA executable in their current directory.  Removing the variable from the test configuration causes it to default to the correct value of `${env.USERPROFILE}\.scubagear\Tools` instead.
Resolves a bug that can impact the ability to run automated testing against Defender settings and decreases the size of the test configurations to just the values necessary for a given test.
Closes #992 
To test that the update configurations work as intended, execute automated testing with the following script and the appropriate test tenant and service principal details set as needed.
1. Run the following from ScubaGear …

Remove default variables from Defender test configs

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/AAD.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml
Testing/RunUnitTests.ps1

Fixed the bug in AAD policy 5.2 user consent to apps, that was reported by multiple users. Microsoft added some data elements to the respective JSON array that broke the Rego logic, so I revised the logic, updated the unit tests to match the new state and updated the functional tests. I also made a minor fix to the RunUnitTests.ps1 to correct a flaw when passing the "-c" control group parameter. 
Closes #1022 
Tested against E5, G5, G3 and GCC High.

Fix bug with msaad52v1 only admins consent to apps

---

.github/workflows/run_update_opa.yaml
PowerShell/ScubaGear/Modules/Support/Support.psm1
README.md

- This PR creates a workflow that will run a periodic job to check if there is an OPA version update. 
- If there is then the workflow will create a PR request that makes the changes necessary to ScubaGear to bump the OPA version. 
- Small changes to the README and Support.psm1 to make both files more parse friendly. 
- Currently does not automatically check if the newest version of OPA is compatible with ScubaGear. Future TODO is to make that part of this workflow. 
Closes #1003 
Related to #698
Example PR created from a scheduled workflow run: [example OPA Update PR](https://github.com/buidav/ScubaGear/pull/37).
You can also fork ScubaGear, specifically this branch, to test this PR or your own fork.
Note that this GitHub action requires write permissions to PRs.
You can configure the …

Add a Workflow to check for OPA version updates

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/Orchestrator.psm1

- Another quick turn around request from our sibling team to include additional data in the `ScubaResults.json` 
- This PR includes adding the Policy Group Names to the `ScubaResults` JSON. 
- Also, includes another request to add the products assessed to the `Metadata` key in `ScubaResults.json`.
Closes #1039
Closes #1040 
Run ScubaGear against any tenant with the `MergeJSON` switch passed in. i.e `Invoke-SCuBA -MergeJSON`.
Look at the resulting `ScubaResults.json` and see if the correct keys and values are present. 
- ~[x] Changes are limited to two goals - *eschew scope creep!*~ Shh

Add Policy Group Names to ScubaResults.json

---

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Testing/Functional/Products/Products.Tests.ps1
Testing/Functional/Products/TestPlans/aad.testplan.yaml
Testing/RunUnitTests.ps1

Updated AAD Rego code  to check for MS.AAD.3.3v1: If Phishing-resistant MFA has not been enforced yet and Microsoft Authenticator is enabled, it SHALL be configured to show login context information.
Closes #410 
Closes #1020 
Changes in detail:
- To code this issue for policy 3.3, we needed to retrieve the authentication method configurations that were already being returned by an existing ScubaGear cmdlet Get-MgBetaPolicyAuthenticationMethodPolicy for policies 3.4 & 3.5 but the JSON structure had to be modified to support all three policies.
- The Rego was updated for policies 3.4 and 3.5 to read from the adjusted JSON structure. Unit tests and functional tests were adjusted accordingly.
- Rego policy 3.5 was adjusted since it was coded wrong - when the policy migration state is not …

Enhance AAD Provider and Rego Code to automate checks for policy MS.AAD.3.3v1

---

PowerShell/ScubaGear/Rego/SharepointConfig.rego
PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego
Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml

Several of the Sharepoint policies execute even in cases when they are not applicable. The policies for Sharepoint 1.3, 3,1, 3.2, and 3.3 have been updated to produce N/A messages when warranted. If the configuration settings apply, then the policy executes normally. 
**Policy 1.3**
- Executes normally when the external sharing slider is set to any value other than Only people in your organization.
- Produces N/A message when set to Only People in your organization. 
- Unit tests updated.
- Functional tests updated.
**Policy 1.4**
- Executes normally when the external sharing slider is set to any value other than Only people in your organization.
- Produces N/A message when set to Only People in your organization. 
- Unit tests updated.
- Functional tests updated.
**Policy 3.1**
- …

Modify Sharepoint policies to only execute when applicable

---

PowerShell/ScubaGear/RequiredVersions.ps1

Manually bump current dependencies until the automated PS version bump workflow in `#1096` is complete 
Did all the needed dependency pull requests into 1 PR. 
Much easier to do this in 1 branch rather than 3 separate ones as juggling different versions for 3 modules became complex.
- Bump max dependency version for Microsoft Teams PowerShell to <= 6.99.99999 (Last possible Major version)
- Bump max dependency version for SharePoint PowerShell to <= 16.0.24810.12000 (Latest version) (Pin)
- Bump max dependency version for MS Graph PowerShell from to <= 2.19.99999 (Latest version) (Pin)
Closes #998
Closes #999 
- For a client that has used ScubaGear before in the `utils` folder run `UninstallModules.ps1` until no more stray PowerShell modules exist on the client.
- Use …

Bump ScubaGear PowerShell module dependency versions 

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1

Add the link to the group markdown anchor (see screenshot) to the ScubaResults.json file.
Closes https://github.com/cisagov/ScubaGear/issues/1118.
Ran against a test tenant and verified that both the links in the HTML and the links in the json worked as expected.

Add reference URL to ScubaResults.json

---

PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
PowerShell/ScubaGear/Rego/DefenderConfig.rego
PowerShell/ScubaGear/Rego/Utils/Defender.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml

Add licenses check for policy groups 2 and 4 in addition to the current check, make the report details more precise. And let user be more aware of the missing licenses. 
closes #599 
Run Scuba for Defender 
Change the json file mainly "defender_license" to "false"
Run Scuba for Defender again 
Will see warning about Defender license missing during the run
Will see notes on reports indicates license missing
Note: the check for policy group 2 and 4 will still pass or fail based on the environment setting because we are modifying the json file from an tenant with required licenses. The result is still be accurate based on the environment information.  Note that, normally it will fail if they don't have license due to missing information from the provider JSON.  
Use `Rebase branch` button …

Enhanced Defender license warnings for policy groups 2 and 4

---

.github/workflows/build_sign_release.yaml
.github/workflows/publish_private_package.yaml
.github/workflows/publish_public_package.yaml

The `azure/login` GitHub action allows our publishing workflows to access our code signing certificate from an Azure Key Vault.  However, GitHub has deprecated azure/login@v1 due to the end of life of Node.js v16 used by this action.  The newer @v2 uses the supported Node.js v20 software and resolves the login issue in our workflows.
The publish workflows that use the azure/login action are failing as the previous version is now deprecated and causing it the login to fail on execution.  Upgrading the action to the latest (v2) resolves the issue.
Closes #1049 
Review the most recent failed `Publish and sign Draft Release` and `Publish public package` action results to see the issue and note the deprecation warning.
See successful results of `Build and Sign Release` workflow on this branch …

Bump azure/login action to v2

---

README.md
docs/configuration/configuration.md
docs/configuration/parameters.md
docs/execution/execution.md
docs/execution/reports.md
docs/installation/uninstall.md
docs/prerequisites/dependencies.md
docs/troubleshooting/graph.md

I made the following changes to improvement the documentation:
- Fixed 404 on Execution
- Converted results on Reports into a table for better readability
- Removed extra space on Parameters
- Replaced <username> with johndoe on Dependencies (and others) for better render.
- Clarified purpose of commented out product values in Typical Use section of Configuration.
- Fixed hyperlink on Execution to jump directly to ProductNames
Closes #1154
Closes #1156 
Previewed changes in VSCode.

Make small improvements to the documentation

---

PowerShell/ScubaGear/Rego/EXOConfig.rego
PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_08_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_09_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_14_test.rego
PowerShell/ScubaGear/baselines/exo.md
Testing/Functional/Products/TestPlans/exo.testplan.yaml

- This PR decouples the remaining baseline policies that had a SHALL AND SHOULD within the same policy statement into their own separate policies.
- Adds rego and functional unit tests for those new policies. 
Policies broken up: 
- MS.EXO.8.1v1
- A DLP solution SHALL be used. The selected DLP solution SHOULD offer services comparable to the native DLP solution offered by Microsoft.
- MS.EXO.8.2v1
- The DLP solution SHALL protect PII and sensitive information, as defined by the agency. At a minimum, the sharing of credit card numbers, Taxpayer Identification Numbers (TIN), and Social Security Numbers (SSN) via email SHALL be restricted.
- MS.EXO.9.1v1
- Emails SHALL be filtered by the file types of included attachments. The selected filtering solution SHOULD offer services comparable to …

Decouple the remaining EXO Shall/Should policies

---

README.md

Add license, GitHub/PSGallery versions, CICD workflow, open issues, and GitHub/PSGallery download badges to the README with respective links.
Resolves #1166  
- Check [remote branch](https://github.com/cisagov/ScubaGear/tree/1166-add-download-badges) to see if badges display correctly, check links.
- Created fork and tested all badges display correctly in GitHub Pages.

Add additional shields.io badges to README

---

.github/workflows/run_update_opa.yaml

- This PR fixes the OPA version bump workflow by removing the code that assumes the old README format and tries to modify it.
Closes #1187
Example PR created from a scheduled workflow run: [example OPA Update PR](https://github.com/buidav/ScubaGear/pull/43).
You can also fork ScubaGear, specifically this branch, to test this PR or your own fork.
Note that this GitHub action requires write permissions to PRs.
You can configure the permissions for this on the repo settings under `Settings` => `Actions` => `General` => `Workflow permissions`. Ensure the options below are selected. 

Fix the OPA version bump workflow to work with the new README

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego

Added user exclusions and group exclusions to AAD 3.7.
Closes #988 
The Rego code for AAD is missing the user and group exclusions 
Actions:

Add policy check for AAD 3.7 to support exclusions -- new

---

PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1

Ensure the `DLPLicense` variable gets defined even if `Connect-IPPSSession` throws an exception.
Closes https://github.com/cisagov/ScubaGear/issues/1191.
- Tested on a tenant with an expired license - results in invalid json on main
- Tested on a tenant with an expired license - exception properly handled on this branch, no malformed json produced
- Tested on a tenant that does not result in an exception - executed like normal as expected

Correct bug with Connect-IPPSSession error handling

---

PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-Caps.Tests.ps1

GitLeaks (in the pipeline) was reporting that we were leaking 3 secrets to our GitHub repo, but these were all false positives.  I added an exception for each of these, and now GitLeaks is no longer reporting them. 
Closes:  #1204 
- Saw the error reports on the `main` branch
- Added the exception code (`#gitleaks:allow`) to the AAD code on a new branch
- Verified that the pipeline ran green

Add exceptions for GitLeaks false positives

---

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/RequiredVersions.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Invoke-GraphDirectly.ps1
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
utils/UninstallModules.ps1

*This PR replaces #1094 which became too difficult to deal with since there were heavy merge conflicts - reference that PR for additional details.
The gist of this pull request was to modify the AAD provider so that we replace the Cmdlets in the Microsoft.Graph.Beta.Identity.Governance Powershell module with direct calls to MS Graph REST APIs. We found that the offending Powershell module takes a significant amount of time to load into memory when you call ScubaGear the first time in a fresh Powershell window. The good news was that the RESP API returns the same fields as the Cmdlet, except that the field names begin with a lower case letter so that is why you see those respective changes in the Rego and unit/functional tests as well as references in the AAD provider. 
closes #816
The …

Boost AAD performance by replacing Cmdlets with slow load times

---

PowerShell/ScubaGear/RequiredVersions.ps1

Updates the `RequiredVersions.ps1` set of Microsoft.Graph.* module dependencies `MaximumVersion` from 2.19.9999 to 2.99.9999.
ScubaGear does not pin modules to specific minor versions unless there is a specific technical issue.  There is no such reason at this time for Microsoft.Graph.*, but the max version prevents minor versions beyond 2.19.  The current version of those modules is 2.19 so future minor versions will not be allowed by ScubaGear unless the max version is updated to allow all 2.x versions.
1. Clear all ScubaGear dependent modules (and ScubaGear itself) from test system
2. Install ScubaGear (or import)
3. Run Initialize-SCuBA
4. Confirm that Microsoft.Graph.* latest version is installed
5. Run `Invoke-SCuBA` and confirm it works as intended (or confirm auto smoke test …

Extend Microsoft.Graph.* dependency max version from 2.19.x -> 2.x.x

---

PowerShell/ScubaGear/baselines/defender.md

Replicates list of activities from MS.EXO.16.1v1 to include when configuring M365 Defender alert policies as per MS.DEFENDER.5.1v1 implementation instructions. 
Previously, readers would have to 'flip' between the two SCBs to follow Defender SCB implementation instructions while referencing Exchange Online alert policy activities list, then back to Defender to finish.  Replicating the list from EXO in the Defender SCB eases the reader burden, makes the implementation instructions more standalone, while retaining the references between the two policy items for awareness.
Closes #565 
This update only includes implementation instruction changes and does not change the contents or meaning of the policies themselves.  Please review both MS.DEFENDER.5.1v1 and MS.EXO.16.1v1 SCBs (prior and …

Fix circular reference between MS.EXO.16.1v1 and MS.DEFENDER.5.1v1 implementation instructions

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
PowerShell/ScubaGear/Modules/Support/Support.psm1
PowerShell/ScubaGear/Sample-Config-Files/ignore_policies.yaml
PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Get-OmissionState.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/ScubaConfig/ScubaConfigLoadConfig.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/New-Config.Tests.ps1
docs/configuration/configuration.md

Make it so that policies can be omitted from the ScubaGear reports.
Closes https://github.com/cisagov/ScubaGear/issues/740.
Closes https://github.com/cisagov/ScubaGear/issues/739.
Closes https://github.com/cisagov/ScubaGear/issues/738.
I'd recommend that the reviewers start by reading the documentation I added for this feature, to get a good overview of the approach taken: https://github.com/cisagov/ScubaGear/blob/739-allow-any-given-policy-to-be-ignored/docs/configuration/configuration.md#omit-policies.
Testing I've done:
- Added 8 new Pester cases to cover these changes
- Manually tested without a config file to ensure normal executions is unchanged
- Manually tested excluding several policies without expiration dates
- Manually tested excluding policies without specifying the rationale …

Allow policies to be omitted from ScubaGear

---

PowerShell/ScubaGear/baselines/teams.md

Add notes to MS.TEAMS.2.2 and MS.TEAMS.3.1 clarifying that the settings are not applicable for GCC, GCC High, or DOD tenants. Make the note consistent with existing note for the policy MS.TEAMS.2.3
closes #1069 

Teams baseline updates for policies #2.2 and #3.1 to add notes

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/AAD.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml

*Note: to make these changes I had to change the name of the TestDriver in the functional tests to "ScubaCached" since that fix was not applied to main yet.
- Fixed 3.2 functional test so that it does not rely on the tenant having a compliant non-specific MFA conditional access policy that matches the conditions for baseline policy 3.2. Instead the test case now uses the special conditional access policy named Automated Test to setup the condition instead, since that is a more reliable method.
- Fixed incorrect functional test cases for MS.AAD.3.7v1. Bug found by Julian on 7/30/2024 when performing testing on a different pull request. The test cases should be using the GrantControls.Operator OR operator but they were using AND. Also because of this change I removed the functional test …

Rectify AAD functional test failures and improved naming of some AAD Rego rulesets

---

.github/workflows/unit_test_opa.yaml
.regal/config.yaml
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego

Hi there! It's been a while :) 
I figured I'd see how the latest Regal release would work here, and it worked just well. Just some minor changes needed:
- Remove rules from config that aren't needed
- Add configuration for new rules (only 'messy-rule' needed)
- Modify 'no-whitespace-comment' config to allow common exception
- Fix 'identically-named-tests' violation by renaming the tests

Update Regal to v0.23.1

---

PowerShell/ScubaGear/Modules/Connection/ConnectHelpers.psm1
PowerShell/ScubaGear/Modules/Connection/Connection.psm1
PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
PowerShell/ScubaGear/Rego/DefenderConfig.rego
PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-GraphHelper.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/DefenderProvider/Export-DefenderProvider.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/Rego/Defender/DefenderConfig_06_test.rego
Testing/Functional/Products/TestPlans/defender.testplan.yaml

Provides enhancement to Defender assessment checks for MS.DEFENDER.6.2v1 to ensure ALL users are assigned an advanced auditing license feature to support the SCB policy item.  The actual update includes:
* A new MSGraph connection helper `Connect-GraphHelper` to modularize connecting to Graph API
* Updates to the Connection module to use the new `Connect-GraphHelper` function
* Connection module updates to connect to Graph when assessing Defender
* Defender provider updates to populate `total_users_without_advanced_audit` count
* New rego assessment checks for MS.DEFENDER.6.2v1 to validate the new count and provide count of users without the requisite license if not zero.
* Additional unit and functional tests to exercise the new assessment check and connection helper
No documentation …

Add assessment check for MS.DEFENDER.6.2v1

---

PowerShell/ScubaGear/Sample-Config-Files/aad-config.yaml
PowerShell/ScubaGear/Sample-Config-Files/basic_config.yaml
PowerShell/ScubaGear/Sample-Config-Files/creds_config.yaml
PowerShell/ScubaGear/Sample-Config-Files/full_config.yaml
PowerShell/ScubaGear/Sample-Config-Files/sample-config.yaml
PowerShell/ScubaGear/Sample-Config-Files/typical_config.yaml

I have formatted the sample config files to be more streamlined. I have also added the other EntraID exclusions that are now available for AAD
The sample configs have been updated and not streamlined in a while and needed a refresh.
I removed extra references to other baselines in baseline specific sample files and added a more detailed and standardized description. This resolves #1075 
Sample config files no code was changed

Cleaning up and streamlining config files

---

.github/workflows/build_sign_release.yaml

The build and sign GitHub release workflow uses some of the same publish code that the publish to PSGallery workflows use (see utils/workflow/Publish-ScubaGear.ps1).  The publish code was recently refactored, but the GitHub workflow was not updated to use the changes.  This PR corrects that oversight.
Closes: #1255 
Future improvements: #1257 
Checked the workflow pipeline.
Published an RC to GitHub.

Fix build and sign GitHub release

---

PowerShell/ScubaGear/Modules/Support/Support.psm1
Testing/workflow/Initialize-ScubaGearForTesting.Tests.ps1

-This PR simply removes lines that were erroring out during a `Initialize-SCuBA` run when ScubaGear is installed from PowerShell Gallery.
**Update 1**
- Interesting [ScubaGear unit test workflow failure](https://github.com/cisagov/ScubaGear/actions/runs/10274430456/job/28433496648) popped up after I committed. Looks like these 3 lines of code were keeping this specific workflow unit test from failing. 
- The error here is because ScubaGear wasn't imported directly by the unit test. Since ScubaGear isn't imported this line `$ModuleParentDir = Split-Path -Path (Get-Module ScubaGear).Path -Parent` would null out and cause the unit test failure. 
- In practice this error won't ever happen to a normal ScubaGear user, since in order use ScubaGear you need to import ScubaGear.
**Update 2**
- …

Remove erroring support module code from Initialize-SCuBA

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Modules/Support/Support.psm1
Testing/Functional/Products/Products.Tests.ps1

This PR fixes the problem when running AAD against GCC high tenants with newer versions of the Graph dependency modules. We started getting 401 Unauthorized errors against GCC high because there was some problem with the token that we traced to Invoke-MgGraphRequest. The fix was to pass the MS graph FQDN prefix when calling that cmdlet and that seems to rectify the  issue.
Closes #1265 
- Test against all tenants, including GCC high.
- Run AAD with other products and by itself.
- Run ScubaGear with a config file as well.

Fix AAD 401 authentication errors against GCC high tenants

---

PowerShell/ScubaGear/Rego/SharepointConfig.rego
PowerShell/ScubaGear/Rego/Utils/ReportDetails.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml

Modified the implementation of Sharepoint 1.4 so that it is "not implemented" in the report since we now have evidence that it is deprecated or at least a user cannot configure it anymore.
Closes #1267 
Tested using interactive authentication and service principal against the E5 tenant. Verified that the report produces the expected output message.

Changed Sharepoint policy 1.4 to not-implemented since it relies on deprecated field RequireAcceptingAccountMatchInvitedAccount

---

.github/workflows/run_pipeline.yaml

Remove the workflow unit tests from the CI pipeline, since they are now in their own pipeline, the workflow pipeline.
Closes #1271 
Removed job.  Re-ran workflow.  Tests still pass.

Remove workflow unit tests from CI pipeline

---

PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
docs/prerequisites/dependencies.md

- Add a backup path to `RunRego.psm1` that checks the user's current executing directory if ScubaGear fails to detect the OPA executable in the `.scubagear/tools` folder.
- This is to assist with troubleshooting when the OPA executable fails to download properly.
Closes #835 
- Remove the opa executable from the tools folder
- Add a copy to your current executing directory. 
- If a copy is not found in both ScubaGear will throw a more detailed error message.

Add a backup path to look for the OPA executable in the current directory

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/Utility/Utility.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ProviderList.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Out-Utf8NoBom.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/New-SCuBAConfig.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Utility/Get-Utf8NoBom.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Utility/Set-Utf8NoBom.Tests.ps1
Testing/Functional/Products/FunctionalTestUtils.ps1
Testing/Functional/Products/Products.Tests.ps1

This update changes ScubaGear such that its tenant configuration captured in the provider output JSON (ProviderSettingsExport.json, by default) is encoded as a UTF-8 file without a byte order mark (BOM) rather than including a BOM.  
Updates to the code include:
* New functions Get-Utf8NoBOM and Set-Utf8NoBOM for reading and writing utf-8 encoded files without a BOM
* Wrapper functions Invoke-ReadAllLines and Invoke-WriteAllLines that provide testability for use of the associated .NET System.IO functions
* A new Utility powershell module for the above functions to support use across ScubaGear modules
* PowerShell unit tests for the new methods covering pathing and escape sequence handling
OPA Rego (as of 0.68) does not recognize the byte order mark (BOM).  As a result, parsing of the file …

Fix encoding issue by removing BOM from provider output files

---

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/RequiredVersions.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/LoadObjectDataIntoPrivilegedUserHashtable.Tests.ps1
utils/UninstallModules.ps1

The general impetus for this PR was a publicly reported edge case where the **AAD provider crashes when an admin assigns a nested group to an AAD PIM group** as an Eligible assignment. In order to implement the fix, I determined that augmenting the current code in Get-PrivilegedUser was a bad idea because it had already become hard to maintain with lots of duplication, so I refactored Get-PrivilegedUser to call a new helper function named LoadObjectDataIntoPrivilegedUserHashtable which takes a user or a group as an argument, fetches the metadata about the object and loads the metadata into the PrivilegedUsers hashtable which is used to form the privileged_users section of the provider JSON document. The other major defect that this PR addresses is that the code now handles a scenario …

Enhance AAD provider to handle nested PIM groups and refactor Get-PrivilegedUser to reduce code duplication

---

PowerShell/ScubaGear/Modules/Orchestrator.psm1
Testing/Functional/Products/FunctionalTestUtils.ps1
Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml

This request contains updates to fix failures when running tests that modify configuration setting export results prior to testing.  Specifically this update:
* Makes sure that Invoke-SCuBACached outputs CSV results for only the configured products
* Modified provider settings file is output to the correct filename
* The filepath of the export settings file is correctly specified when writing to disk
* Modifies two MS.SHAREPOINT.2.1v1 test pre-conditions to ensure strict ordering
Some testing requires manual changes to represent uncommon or undesirable test results.  Doing so means the functional test harness may intercept and change those results before running a test.  The bug was preventing the modified results from being used in the tests and causing tests to fail when they should …

Fix functional testing and cached output errors

---

PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html
PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ReportCreation.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ScubaCached.Tests.ps1

Add UUID to the JSON output (both raw provider output and ScubaResults.json).
Closes #1336.
I performed the following tests:
1. `Invoke-Scuba`. Worked as expected.
2. `Invoke-Scuba -KeepIndividualJson`. Worked as expected.
3. `Invoke-ScubaCached -ExportProvider $false` with input generated without the `KeepIndividualJson` flag. Worked as expected.
4. `Invoke-ScubaCached -ExportProvider $false` with input generated with the `KeepIndividualJson` flag. Worked as expected. ~~(assuming you manually fix #1329 as #1334 hasn't been merged yet)~~.
5. `Invoke-ScubaCached -KeepIndividualJson -ExportProvider $false` with input generated without the `KeepIndividualJson` flag. Worked as expected.
6. `Invoke-ScubaCached -KeepIndividualJson -ExportProvider $false` with input generated with the …

Add UUID to JSON output

---

PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1
PowerShell/ScubaGear/Rego/SharepointConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego
Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml

- Removed `input.OneDrive_PnP_Flag == false/true` statements and Not-Implemented test in `SharePointConfig.rego`. The `input.OneDrive_PnP_Flag` is still used in the SharePoint unit tests to indicate spo/pnp variants
- Removed unnecessary fields from `sharepoint.spo.testplan.yaml` to get rid of warnings; removed deprecated parameter ("Detailed"=$true) from Get-SPOSite and Get-PnPTenantSite in SharePoint provider
- Expanded unit test coverage for SharePoint 3.2 to cover service principal cases in `SharepointConfig_03_test.rego`; expanded functional test coverage for SharePoint 3.2 in the `sharepoint.pnp.testplan.yaml`
- Logic for SharePoint 3.1 fixed to account for negative integer value, -1, when the Anyone links checkbox is not set. The policy now displays a fail for this case
- Set …

Add policy check for SharePoint 3.2 when using service principal and update SharePoint 4.2 rego for deprecation

---

.github/actions/extract-email/action.yaml
.github/actions/get-thumbprint/action.yaml
.github/actions/import-pfx/action.yaml
.github/actions/test-product/action.yaml
.github/workflows/check_security.yaml
.github/workflows/clear_cache.yaml
.github/workflows/function_test_defender.yaml
.github/workflows/function_test_entra.yaml
.github/workflows/function_test_exchange.yaml
.github/workflows/function_test_powerplatform.yaml
.github/workflows/function_test_sharepoint.yaml
.github/workflows/function_test_teams.yaml
.github/workflows/publish_private_package.yaml
.github/workflows/run_pipeline.yaml
.github/workflows/run_workflow_pipeline.yaml
.github/workflows/test_production_function.yaml
Testing/Linting/MegaLinter/.checkov.yml

There are several improvements to the nightly functional tests that are all rolled into this PR:
* Publish to the private gallery, thus ensuring that our code is in a state that can be published to PSGallery.
* Email TCOs for each failing set of tests, thus allowing them to know when there are issues that may need their attention.
* Use GitHub caching, thus speeding up testing time by only installing GitHub and various dependencies once.
* Handle concurrency problems within a run by using GitHub's "needs" features for product/tenant pairing, thus ensuring testing one variant doesn't mess with testing a different variant.
* Handle concurrency problems between runs by using GitHub's "concurrency" features for product/tenant pairing, thus ensuring that one tester doesn't mess with the tests …

Improve nightly functional tests

---

.github/workflows/test_production_function.yaml

Added the fromJSON method to parameter calls for booleans.
Closes: #1381 
Ran nightly tests manually with and without checking for email.

Fix syntax error bug in nightly functional test workflow

---

PowerShell/ScubaGear/baselines/aad.md

Updated the implementation guide to follow template of other CAP making it easier on user
closes #982 
Read the updated verbose, and ensure it is clear and accurate directions

Adding Conditional Access Policy Implementation Instructions to AAD 1.1

---

PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1

This PR fixes a bug in Defender that is observed in larger tenants. Defender runs a query via Get-MgBetaUser to get a count of users that do not have the advanced auditing feature assigned to them. Instead of just retrieving the count from the REST API, the current query downloads all the users that match the filter. If a tenant has thousands of users without advanced audit this can result in significant slowness. I added the Top = 1 parameter so that only a single record is returned and verified that the count still works. See the linked issue below for full details and screenshots.
Closes #1404 
See the screenshots in the linked issue above for details on the before and after testing that I performed with the fix against a tenant with over 2,000 users.
Use `Rebase branch` button below …

improve performance of Defender query to count users without advanced auditing

---

docs/execution/execution.md
docs/installation/github.md

Added a section on importing the module before installing dependencies.
Closes: #1411 
Viewed the docs on GitHub

Correct omission in documentation about importing module when downloading from GitHub

---

.github/workflows/convert_baselines.yaml

This PR converts the existing baseline files that are in Markdown to both HTML and text format.  It saves them to the baselines folder and then makes that folder available as an artifact.
Closes: #1376
Wrote and tested original workflow in an [alternate repository](https://github.com/james-garriss/test-markdown-to-html).
Once workflow was working, moved to SG repo and modified accordingly.
Verified expected results were found in the artifact.

Convert baseline markdown files to text and HTML

---

PowerShell/ScubaGear/Modules/Support/Support.psm1

- Add `$Scope` to Initialize-SCuBA to let users install to `AllUsers`, a place where all users can access the dependent PowerShell modules, rather than just the `CurrentUser` on their system. 
Closes #882 
- Run `Initalize-SCuBA` by itself. Should be the normal behavior.
- Then run `Initialize-SCuBA -Scope AllUsers`. 

Allow Users to Specify Installing to AllUsers via new $Scope Variable in Initialize-SCuBA

---

PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1

- Make  `DefaultOutPath` work on UNC file systems.
- Add a try catch to the `DefaultOPAPath` assignment. 
Closes #1315 
Closes #1369 
- Try to run `Import-Module .\PowerShell\ScubaGear` on a non-Windows system.
- Try to run  `Import-Module .\PowerShell\ScubaGear` on system using UNC file paths.

Correct Erroring Default Variable Assignments on Systems with unique file paths

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_05_test.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml

Update rego for MS.AAD.5.4v1 to not-implemented as the group consent setting is discontinued.
In case the setting is not discontinued in other Azure implementations (e.g. GCC), the rule will continue to function as expected.
Changes the tests to not-implemented to avoid falsely failing a test that can no longer be performed. The baseline can be removed in a future release.
Closes #1139
Run AAD tests and verify that the test result for MS.AAD.5.4v1 is N/A instead of failed and criticality is not-implemented. Ensure tests can still successfully run.

Change tests for MS.AAD.5.4v1 for teams group consent to not-implemented as setting is deprecated

---

PowerShell/ScubaGear/Modules/Connection/Connection.psm1
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportDefenderProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ExportTeamsProvider.psm1
PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1
PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/ConvertTo-ResultsCsv.Tests.ps1

Added the Powershell error stack trace to numerous locations in the source code to assist when troubleshooting bug reports.
I removed the try catch {} blocks in the following functions since the calling functions handle the stacktrace now: Get-PrivilegedUser, Get-PrivilegedRole, Invoke-Rego.
Closes #1344 
I tested an error scenario or two for each of the functions that I modified to add the stacktrace and verified that the error information was displayed as expected. Results are documented in this PR.
- Perform a code review to determine if any tweaks need to be made
- Conduct hands on tests by simulating error conditions and verify that ScubaGear prints the error message and stacktrace. You can use my test results as inspiration.
Use `Rebase branch` button below or use …

Added StackTrace multiple locations in source code to assist when troubleshooting

---

PowerShell/ScubaGear/CheckVersion.ps1

The version check code has a reference to a removed variable still present. This PR deletes it and closes #1480 
Deleted two lines of code writing out the version check file, which was removed for Kraken.
Currently this bug causes a error and stack trace on import.
Closes #1480 
```
Invoke-WebRequest -Uri "https://github.com/cisagov/ScubaGear/releases/download/v1.3.0/ScubaGear-1.3.0.zip" -Outfile scuba-1.3.0.zip
Expand-Archive -Path "scuba-1.3.0.zip" -DestinationPath "scuba-1.3.0"
Copy-Item -Path "{path to git checkout}\Powershell\ScubaGear\CheckVersion.ps1" -Destination "scuba-1.3.0\Powershell\ScubaGear\CheckVersion.ps1"
Import-Module "scuba-1.3.0\Powershell\ScubaGear\CheckVersion.ps1"
```
Alternatively, you can just decrement the ModuleVersion in the scuba manifest and import from the …

Remove reference to removed VersionCheckFile

---

docs/configuration/configuration.md

Expands the existing Defender Configuration section in the docs/configuration.md documentation file to explain the existing Defender policy-specific configuration file options, what they represent, and how to use them.
Closes #1134 
This is a documentation only update.  The testing is to manually review the updated documentation for grammar, spelling, and clarity.  
Additional testing would include running ScubaGear with the example Defender configuration file referenced in the documentation, adjusting the various policy-specific variables referenced in the documentation to confirm what is said in the docs matches the expected operation in ScubaGear.
Note this update includes converting config page absolute links to relative links when referencing sections in the same document or sample …

Add Defender configuration options documentation

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
docs/configuration/configuration.md

Changes the header in the `CreateReport.psm1` module that generates the header of the Entra HTML report so no longer references the README file, but rather the overall documentation.  Also adds a sentence to better explain what an exclusion is and why it is useful.
The Entra report should provide up-to-date and accurate information for users to understand their options and point to the current documentation.
Closes #1457 
Run `Invoke-SCuBA -p aad` with valid credentials to generate an Entra HTML report.  View the report and verify that the new language is visible, correct, and the new link works.
(Note: Only …

Revise Entra report header with new exclusion info and documentation name

---

PowerShell/ScubaGear/RequiredVersions.ps1

Updated [RequiredVersions.ps1](https://github.com/cisagov/ScubaGear/blob/1409-update-microsoftpowerappsadministrationpowershell-to-v20200/PowerShell/ScubaGear/RequiredVersions.ps1) file to update the Microsoft.PowerApps.Administration.PowerShell minimum and maximum versions to support pinning to versions newer than the bugged 2.0.197 version.
* Min version set to 2.0.198
* Max version re-pinned to 2.0.203
Allows users to use newer working versions of the PowerApps admin module while preventing installation of the 2.0.197 bugged version.
Closes #1409 
- Remove existing ScubaGear dependencies from your test machine.  Either by running `Uninstall-Module` for each dependency OR go to your Documents/WindowsPowerShell/Modules folder and delete all ScubaGear dependent modules.
- Import the …

Updated Microsoft.PowerApps.Administration.PowerShell min/max versions

---

.github/workflows/build_sign_release.yaml
.github/workflows/publish_private_package.yaml
.github/workflows/publish_public_package.yaml
Testing/workflow/Build-SignRelease.Tests.ps1
Testing/workflow/Install-AzureSignTool.Tests.ps1
utils/workflow/Build-SignRelease.ps1
utils/workflow/Install-AzureSignTool.ps1
utils/workflow/Publish-ScubaGear.ps1

Moved some of the build and sign release into a function.  Reused existing unit tests and wrote a new one.
Note:  Testing Azure Sign Tool itself should be a functional test that is added to nightly tests.  A new issue was created for this (#1520).
Closes: #1453 
Ran workflow pipeline, checked the results.

Write unit tests for build and sign release

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/AAD.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_01_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_02_test.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego

This PR modifies the Rego for all conditional access policies **prohibit role exclusions and application exclusions**. It also ensures that these **checks are applied in a consistent manner** across all 8 relevant policies. We removed the PolicyConditionsMatch ruleset because there was no easy way to consistently call it from all 8 policies due to minor differences in the checks so instead we opted for creating a common section of code that was placed into each policy.
Closes #1170 
Closes #1323 
**These instructions are OBE because we are checking guest user exclusions anymore. Testing was performed with role exclusions and application exclusions**
To test, within the conditional access policies, inside of users, inside the ExternalGuestorExternalUsers, update the MembershipKind and the …

Add Rego checks for Application & role Exclusions and be consistent across Conditional Access Policies

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html
PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1
PowerShell/ScubaGear/RequiredVersions.ps1
Testing/Functional/SmokeTest/SmokeTest002.Tests.ps1

Wanted to add privileged service principals to the report to make users aware of these high privileged principals within their tenants
#934 
Test with different tenants and ensure the Privileged Service Principals table is produced as expected for the AAD report and verify the verify `privileged_service_principals` is added in ScubaResults.json.

 Add privileged service principals table to AAD report

---

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/EXOProvider/Get-ScubaDmarcRecord.Tests.ps1

Program ScubaGear to ignore the coexistence domain for the DMARC controls in the EXO baseline.
Closes #1514.
I did the following:
- Tested on a tenant with a coexistence domain, worked as expected
- Tested on a tenant without a coexistence domain, no change, as expected
- Updated Pester unit tests
Before:
After:

Ignore coexistence domain for the DMARC controls

---

.github/workflows/publish_private_package.yaml
PowerShell/ScubaGear/Modules/Support/Support.psm1
Testing/workflow/Initialize-ScubaGearForTesting.Tests.ps1
utils/workflow/Initialize-ScubaGearForTesting.ps1
utils/workflow/Publish-ScubaGear.ps1

Added tests for checking the textual outputs that result from running ScubaGear's most basic commands:
```
Install-Module -Name ScubaGear
Initialize-SCuBA = check for outputs
Invoke-SCuBA -Version
```
The idea is to add additional checks to make sure SG is running as expected.
Closes #1490 
The tests for Initialize-Scuba can be found by running the workflow pipeline and checking under Workflow Units Tests for the Pester Test called "Describing Initialize-ScubaGear Output Check." There should be 3 successful tests:
- PSGallery should be trusted
- OPA should be downloaded
- Setup time should be minimal
The tests for Install-Module can be found by running the nightly functional tests (test_production_function.yaml), finding the first job (publish package/private repo), and checking under …

Test the output of ScubaGear's basic commands

---

PowerShell/ScubaGear/Rego/TeamsConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/Teams/TeamsConfig_05_test.rego

Teams policies MS.TEAMS.5.1v1 - MS.TEAMS.5.3v1 deals with application permission policies - in case of a failure ScubaGear generates a warning message (since this is a SHOULD policy). Currently the warning message correctly identifies the offending policies but incorrectly indicates them as meeting policies. This PR is to change warning message to correctly identify them as app permission policies. 
Closes #1495 
Run ScubaGear against a tenant. Configure the tenant to fail the TEAMS.5.1v1. Make sure that the scubagear results report correctly identifies the result for 5.1 and the warning message correctly identifies the offending 'app permission policy'.
Warning message before the fix:
Warning message after the fix:
Use `Rebase branch` button below or use …

MS.TEAMS.5.xv1 - update warning message to reflect the correct reason for the policy fail (public reported issue)

---

PowerShell/ScubaGear/Modules/Support/Support.psm1
PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/KeyFunctions.rego
PowerShell/ScubaGear/Sample-Config-Files/aad_config.yaml
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
PowerShell/ScubaGear/baselines/aad.md
Testing/Functional/Products/TestPlans/aad.testplan.yaml

This pull request creates a new Entra Id baseline policy 3.9 which checks for a conditional access policy that blocks device code authentication. It includes changes to the baseline document and the code.
*Ancillary changes: Upon working on the Rego unit tests I identified an issue with one of the Rego helper functions related to unit tests so I corrected it since it was a minor tweak. The Rego ruleset TestResultContains in /Rego/Utils/KeyFunctions.rego was modified to fix the fact that the print message for the Checking RequirementMet section was printing the values backwards so I re-arranged the order.
Closes #1600 
1. Setup a conditional access policy that blocks device code authentication as per the instructions section in the baseline document for 3.9
2. Run ScubaGear and ensure that …

Create new Entra Id policy 3.9 block device code authentication

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Get-RegoResult.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Get-TestResult.Tests.ps1

Save what the result would have been for controls that are omitted if they had not been omitted to the JSON output (HTML output is unchanged). Two new keys are added for each test result:
- `OmittedEvaluationResult`: What the result would have been, e.g., "Fail"
- `OmittedEvaluationDetails`: What the report details string would have been, e.g., "1 agency domain(s) found in violation: example.com"
For tests that are not omitted, those keys will be set to "N/A". See screenshot below for an example.
Closes #1458.
- Add 12 new unit tests
- Ran ScubaGear with a control omitted, ensured that
- The HTML output is unaffected by the new JSON keys
- The `OmittedEvaluationResult` and `OmittedEvaluationDetails` values are correct for the omitted control.
- The `OmittedEvaluationResult` and …

Save omitted rego evaulation results

---

PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
PowerShell/ScubaGear/Modules/Support/Support.psm1

This update bumps ScubaGear's Open Policy Agent (OPA) executable version dependency so that:
- OPA v1.2.0 is the new default version
- OPA v1.1.0 is retained as an acceptable version
Smoke test results [here](https://github.com/cisagov/ScubaGear/actions/runs/14228121494).
- Bump to the latest OPA version v1.2.0 
- Currently a human should still check if bumping the OPA version affects ScubaGear.
Recommend running `Invoke-SCuBA` with previous OPA version first and save results.
Then running `Initialize-SCuBA` on your system to confirm that the upgrade process installs OPA v1.2.0 on your machine and succeeds at SHA256 check.  Then running ScubaGear on test tenant with new OPA installed.  Compare results from previous run to validate there are no unexpected result changes and inspect for any …

Bump OPA version from v1.1.0 to v1.2.0

---

Testing/Functional/Products/TestPlans/defender.g5.testplan.yaml
Testing/Functional/Products/TestPlans/defender.testplan.yaml

This update changes Defender functional test plan preconditions so they no longer rely on a connection to the MSGraph API. Instead, user and group information is retrieved with equivalent Exchange API calls.
Changes fix failing defender functional tests so developers can get accurate test results.
Closes #1665
Either run the functional tests workflow on this branch or manually run the Defender standard and G5 variant functional tests to validate that the tests run successfully.  No changes were made to G3 tests.
Run the tests against all test tenants.  You may filter testing down to the policies with changes tests by adding `-Filter "MS.DEFENDER.1.[24]*` for the standard test plan and `-Filter "MS.DEFENDER.1.[35]*` for the G5 variant.
If using ScubaGearCheck.ps1, for example, run the …

Fix Defender functional test errors

---

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js
PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css
PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
PowerShell/ScubaGear/Modules/Orchestrator.psm1
PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
PowerShell/ScubaGear/Sample-Config-Files/annotate_policies.yaml
PowerShell/ScubaGear/Sample-Config-Files/omit_policies.yaml
PowerShell/ScubaGear/Sample-Config-Files/scuba_compliance.yaml
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Add-Annotation.Tests.ps1
PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/Get-OmissionState.Tests.ps1
docs/configuration/configuration.md
docs/configuration/parameters.md

- Add capability to mark failed controls false positives
- Add capability to annotate control results
- Add warnings for BOD submission requirements (i.e., document failing policies and `OrgUnit`)
Closes #1733.
- Comment on passing control
- Comment on failing control
- Comment on a warning control (SHOULD)
- Don't comment on warning controls
- Comment on failing control and mark it a false positive
- Don't comment on all failing controls
- Don't comment on all failing controls and use `-SilenceBODWarnings`
- Omit a control
- Comment on an omitted
- Omit a control without providing a justification control
- Don't comment on a failing control you marked a false positive
- Mark a passing control a false positive
- Don't specify `OrgUnit` or `-SilenceBODWarnings`
- Don't specify `OrgUnit` …

Add capability to annotate controls

---

PowerShell/ScubaGear/Rego/AADConfig.rego
PowerShell/ScubaGear/Rego/Utils/AAD.rego
PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Testing/Functional/Products/TestPlans/aad.testplan.yaml

This PR checks authentication strength capability for AAD 3.2v1 which wasn't previously done by ScubaGear 
Closes #1683
This was a public reported bug and was a capability that ScubaGear needed to add, since it was causing false negatives in the compliance of policy 3.2v1
I tested it by changing settings via cached scuba runs and it can be tested by directly changing the CAPs themselves or by updating the json and running it via that. I also ran against the different tenants and ran the unit tests.

Add Authentication Strength Capability for AAD 3.2v1 
