cisagov/ScubaGear

.github/workflows/run_opa_tests.yaml, Rego/AADConfig.rego
Also:
* remove unused assignment as reported by the check
* bump version of checkout and setup-opa actions
* remove invalid "branches" attribute from pull_request_review event
Signed-off-by: Anders Eknert <anders@eknert.com>
Came across this repo earlier today, and I love it :) While looking at the policies, I was curious to see whether they would pass the OPA [strict mode](https://www.openpolicyagent.org/docs/latest/strict/) checks, and with one exception, they did. Fixed that, and updated the CI pipeline to include that check for the future.
/ Anders, OPA maintainer 
**not sure where to find these?**
**that link is a 404**
=> Add `opa check --strict` task

Rego/TeamsConfig.rego
Cmdlet in Teams rego 2.10 for teams was originally associated with Get-CsTeamsMeetingPolicy for error handling 
Changed to CsTeamsMeetingBroadcastPolicy to reflect the actual cmdlet
Closes #33, #32 
Error-handling now display properly 
Ran RunUnitTests.ps1 without errors
=> Update cmdlet for Teams 2.10

PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1, PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1, Rego/AADConfig.rego, Testing/Unit/Rego/AAD/AADConfig2_04_test.rego, Testing/Unit/Rego/AAD/AADConfig2_06_test.rego, Testing/Unit/Rego/AAD/AADConfig2_07_test.rego, Testing/Unit/Rego/AAD/AADConfig2_18_test.rego
- Updated all of the ConvertTo-Json calls to use the current syntax
- Wrapped all API calls inside the `TryCommand` function
- Updated Rego so that it always expects provider output items to be lists
Closes #83, #68, and #19.
- Ran code against Test Tenant 1 (G5) on both main and this branch, closely comparing output and ensuring that all differences are expected.
- Ran code against Test Tenant 2 (G3) on both main and this branch, closely comparing output and ensuring that all differences are expected.
- Ran code in Test Tenant 4 (E5) as an unprivileged user to generate errors. Ensured that all errors generated were handled correctly.
- Ran code in Test Tenant 4 (E5) as an admin after deleting all conditional access policies. Was able to reproduce the error described in #19 in main; bug …
=> Add AAD Error Handling

PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1, Rego/PowerPlatformConfig.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_01_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_02_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig2_03_test.rego
- Updated all of the ConvertTo-Json calls to use @() syntax
- Wrapped all possible API calls inside the TryCommand function
- Wrap API calls that could not be wrapped inside the TryCommand function with a custom try catch (Calls that returned HTTP 403 when erroring)
- Updated Rego so that it always expects provider output items to be lists.
- Updated Rego to handle cases where some tests will pass even when there is a definitive error.
- Display a detailed warning if incorrect $M365Environment parameter value is passed into Power Platform.
Closes #67 
Closes #81
Closes #69
- Ran code in this branch against Test Tenant 1 (G5) with a User with the Power Platform Admin role with a Power Apps License. No Issues.
- Ran code in this branch against Test Tenant 1 (G5) with an unprivileged user …
=> Add error handling for Power Platform

PowerShell/ScubaGear/Modules/CreateReport/BaselineTitles.json, Rego/AADConfig.rego, Testing/Unit/Rego/AAD/AADConfig2_04_test.rego
Update AAD 2.4 Baseline Policy Title to Reflect that Phishing-Resistant MFA SHALL be Required for all Users
Changes made to policy requirement definitions (AADConfig.rego & BaselineTitles.json) and unit test (AADConfig2_04_test.rego)
This change is required because Phishing-Resistant MFA is the new requirement per OMB M-22-09.
I tested this by running the AAD 2.4 unit test, and also running the Invoke-SCuBA for aad, and verifying the title for 2.4 was updated correctly.
=> 113 aad 24 title outdated

PowerShell/ScubaGear/Modules/Connection/Connection.psm1
Fix the authentication endpoint for connecting to GCC Tenants via Service Principal Auth with the $M365Environment included in the parameter arguments.
To fix an edge case #146 did not address.
- Ran code in this branch against Test tenant 1 (G5) via Service Principal auth with all products. (Remember to add the $M365Environment parameter :))
- Ran code in this branch against Test tenant 1 (G5) with regular interactive login against all products.
=> Fix wrong SPO GCC endpoint when using Service Principals

.github/workflows/run_opa_tests.yaml
This PR updates the testing pipeline to use OPA engine version <0.50 by modifying the `Setup OPA` job from version defined as `latest` to `<0.50`.  
The goal is to prevent use of the newest major version, 0.50.0+, which introduces new strict mode tests that prevent the current Rego code from passing its checks.  This is meant as a workaround until the code can be updated to address the newer strict mode checks.
Closes #192 
Made proposed change to `run_opa_tests.yml` to pin version to <0.50 and manually ran the action on the fixed branch.  Result was that the action used OPA v0.49.2 and ran without errors.  Confirms that changing version from `latest` to `<0.50.0` functions as a viable workaround.
To test, go to the GitHub Actions tab on the repository.  Select the `Run OPA tests` action …
=> Restrict OPA tests action to version <0.50

PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
- Added function that performs a more robust DNS lookup for the Exchange Online SPF, DKIM, and DMARC checks
- The function will attempt to perform the DNS lookup over traditional DNS, then again over DNS over HTTPS in the event of failure.
- The function can be configured to retry each query _x_ amount of times.
- The appropriate warning will be displayed to console when needed. Additionally log info is saved into the ProviderOutput json.
- If both DNS channels fail (e.g., network failure, not NXDomain), an exception will be thrown and the report will indicate that an error occurred
Closes #41.
- Tested on my personal computer
- Tested from a CISA machine (as Ethan indicated https://github.com/cisagov/ScubaGear/issues/41#issuecomment-1411086060, some DNS weirdness can be observed there)
- …
=> Add DNS retry

.github/workflows/run_opa_tests.yaml, PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1, PowerShell/ScubaGear/Modules/RunRego/RunRego.psm1
- Improves the Orchestrator's error handling when exceptions occur. 
- Limited the scope of this PR to just wrapping the main Provider/Rego/Report creation functions in the orchestrator within a try/catch. More changes needed to be made within the Provider modules themselves (Defender) to omit a Provider with a thrown exception from the report. This will be a future TODO.
- Small modification to Power Platform Provider error handling to test the orchestrator error handling mechanism.
- Minor `-ErrorAction` additions to functions in Invoke-SCuBA  and Invoke-Rego.
~Partly addresses #66 but does not address the main crux of the issue which is inconsistency between providers.
so leaving this to be addressed another time.~
Made some updates enforce the provider exceptions to be handed …
=> Improve the Orchestrator Error Handling 

Rego/OneDriveConfig.rego, Testing/Unit/Rego/OneDrive/OneDriveConfig2_01_test.rego, Testing/Unit/Rego/OneDrive/OneDriveConfig2_02_test.rego, Testing/Unit/Rego/OneDrive/OneDriveConfig2_03_test.rego
Update Onedrive 2.2 & 2.3 to report manual check required if using service principal.  Update unit test for Onedrive 2.1, 2.2, and 2.3 to check for Service Principal usage. 
One drive reports details were blank for 2.2 and 2.3.   
Checked with unit test.  
.\opa_windows_amd64.exe test .\Rego .\Testing\Unit\Rego\OneDrive -v
Executed Invoke-Scuba with Service Principal. 
Verify Onedrive detailed report for 2.2 & 2.3 indicate to use manual check
=> Onedrive with Service Principal

README.md
This change updates README.md to provide more accurate instructions for invoking signed powershell artifats.
Dolphin includes code signing, which changes the instructions for running the module.
CodeSigning will be retested as part of release testing.
=> 128 update README.md for PowerShell execution policies

.github/workflows/run_release.yaml
The `Build and Sign Release` action produces a draft release with a Git tag format that does not match the previously used release tags and is inconsistent with convention.  This PR addresses the issue by prefixing the new git tag with the letter 'v' consistent with previous versions and general convention.
This change ensures that future generated releases are tagged consistent with previous releases and convention.  
Closes #223 
Run the Build and Sign release action manually on the feature branch.  Validate that the generated draft release includes a tag name that is prefixed with 'v'.
=> Add 'v' prefix to release tag name automation

PowerShell/ScubaGear/Modules/Orchestrator.psm1, Testing/Unit/PowerShell/Orchestrator/Invoke-ReportCreation.Tests.ps1, Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
Allows for execution of Invoke-Scuba with or without invoking browser to automatically show report.
Closes #272 
Allows execution of Invoke-Scuba on systems without default application support for HTML files. 
Adds support option for Windows Server Core by using -Quiet switch 
1) Executed Invoke-SCuBA with and without -Quiet switch.
Without: Show report in browser
With: Does not show report in browser but report is on file system (can bring up manually) 
2) Execute Unit Test 
Additional test cases added to check Quiet is passed appropriately
3) Smoke test will need to pass before promoting Emerald branch to main. Expect some missing test result for now.  
=> Add quiet mode for invoke-scuba

baselines/defender.md
Markdown changes for reversing stance on the Defender preset policies (https://github.com/cisagov/ScubaGear/issues/266). Seeking feedback on baseline document changes only. Code changes will be addressed in a later issue (https://github.com/cisagov/ScubaGear/issues/354).
Summary of changes:
- Removed controls that are now OBE
- Fleshed out policy for 2.1 (ended up being a bit more complex than we initially discussed, I expanded it so that it more closely aligned with the admin center)
- Renamed "Phishing Protections" to "Impersonation Protection," as the other controls in that group were OBE and impersonation protection was all that was left
- Moved DLP group back as impersonation protection is configured on the same page in the admin center as the preset policies
- Adjusted 2.2 and 2.3 …
=> Invert Stance on Defender Preset Policies in Markdown

.github/workflows/run_markdown_check.yaml
Updates the file path to Pester CreateReport unit tests in the `Markdown Check` GitHub action workflow file to match the actual file path in the repository.
The `Markdown Check` action makes sure that the policy baselines included in the ScubaGear repository match the expected format with all the intended policy groups and items.  The check, however, was failing due to a change in the unit test file path structure that wasn't propagated to the shell command in the GitHub action.  This caused the `Invoke-Pester` command to fail, but the action still reported itself as passed with the error as an annotation.  
This needed to be fixed to ensure that any markdown format issues are addressed prior to merge for baseline updates.
Fixes #366 
To test that the updated action works, create a test …
=> Bug fix for Markdown Check action

CONTENTSTYLEGUIDE.md
updated examples and comment instructions
Out of date
closing #364 
- none needed
=> Updated Content Style Guide for Rego

baselines/onedrive.md
Baseline changes based on the comment matrix 
Main changes includes:
1. reformat the baseline document
2. update outdated implementation steps 
3. updated outdated links 
4. remove 2.4, 2.5, 2.6 ,2.7
- 2.4, 2.5, 2.6 (https://github.com/cisagov/ScubaGear/issues/30#issuecomment-1579253290) 
- 2.7 legacy authorization is decided to be removed 
5. split policy 2.3 
6. changing policy to include more restricted options 
Closes #290
Closes #264 
Closes #263 
Closes #261
Baseline changes based on the comment matrix 
I tested these changes by going to the admin portal and trying to follow the implementation steps from the baseline document. When I was unable to find these settings I removed the baselines from the document.
-->
=> One drive baseline

baselines/defender.md
The changes here update the Defender Secure Configuration Baseline data loss prevention (DLP) policies to include the following:
- Clarification on the role of confidence levels relative to sensitive information (#280)
- Adds policy item to configure blocking access by restricted apps (#283)
- Adds rationales for DLP policy items
- Separates and updates implementation steps on a per policy item basis to conform to new style format
These changes were made based on feedback on the existing Defender policy and changes to Defender configuration via the M365 compliance admin portal.  Additional changes were made to accommodate changes to the overall baseline policy format.
Closes #280
Closes #283
To test the implementation steps, sign in to the [Microsoft 365 …
=> Defender Baseline DLP Policy Updates

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1, Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json, Testing/Unit/PowerShell/CreateReport/Import-SecureBaseline.Tests.ps1, Testing/Unit/PowerShell/CreateReport/New-Report.Tests.ps1
Update secure baseline parser to properly identify Policy Id and not pick up Policy implementation sections.  
Updated unit test to accomidate changes.
Required to properly parse secure baseline documents. 
closes #405 
1) Execute Unit test for CreateReport - Verify no errors
2) Execute Invoke-Scuba on all products - verify report policy id, description, etc. 
=> Update Secure Baseline parser (for Policy Id)

PowerShell/ScubaGear/Modules/Orchestrator.psm1, Rego/TeamsConfig.rego, Testing/Unit/Rego/Teams/TeamsConfig2_07_test.rego
Teams email integration is only available in commercial environments. However, at least one user has reported the tool falsely reporting email integration as enabled in a GCC environment and existing code did not probably handle GCC-high tenants.
Changes made:
- Expose the $M365Environment setting to the Rego
- Adjust the Teams Rego to automatically pass the team email integration check if $M365Environment is not set to "commercial".
- Adjust the Teams unit tests for this change
Closes #259.
- Tested on E5 environment with email integration enabled with $M365Environment set to "commercial"
- Tested on E5 environment with email integration disabled with $M365Environment set to "commercial"
- Tested on E5 environment with email integration enabled but $M365Environment set to "gcc"
- Tested …
=> Teams email integration patch

baselines/powerplatform.md
@nanda-katikaneni and @rgbrow1949 had to remake to this PR. Carry on with the review.
@rgbrow1949  reapprove or strike me down if you see anything else I need to change.
@nanda-katikaneni addressed your comments from the last PR. Please rereview
- Reformatted the baseline document with new structure and policy identifiers
- Added additional language and resources in the intro to address pilot feedback
- Added a new Policy Group for Power Pages
- Refine and update policy statements to address pilot feedback. 
- Updated implementation steps for any out of date instructions
TODO: address code updates in #399
closes #239 
closes #287
closes #311 
- Retested instructions for the Power Platform policies on commercial and GCC tenants.
- Addressed comments in the comments matrix.
in code …
=> Address Power Platform pilot comments and substantive changes in the baseline document Part 2

PowerShell/ScubaGear/RequiredVersions.ps1
Updates minimum EXO PowerShell module version in `RequiredVersions.ps1` to `3.2.0`
The broken check is the broken Graph Authentication module from #437
Closes #439 
- Ran `Invoke-SCuBA` with all products with current EXO PoSH module version `3.1` against G3, G5, E5, and GCCHigh tenants. Still needed basic auth enabled on the client. 
- Then ran the below commands to upgrade to EXO PoSh module version `3.2`
```
Uninstall-Module ExchangeOnlineManagement
.\SetUp.ps1 # Installs the latest acceptable version of all PowerShell modules including EXO 3.2
```
- After that, tested against G3, G5, E5, and GCCHigh with both interactive auth and service principal auth. No issues found except the one mentioned in the next bullet. Basic auth is NOT needed on the client. WOO!
- Defender still doesn't …
=> Update EXO PowerShell module minimum version to 3.2

.github/workflows/run_powershell_tests.yaml, .github/workflows/run_smoke_test.yaml
Add step to action to remove pre-installed Microsoft,Graph version 2.0 from image. Will need to remove when #205
closes #437
Fix "Run PowerShell Test" action to work with baseline.
This is a PR off main branch.  Will close #443 off of Emerald branch.  PR should be merged into main and then rebase emerald to include fix.  
Manually execute GitHub action, "Run PowerShell Tests" . Verify Microsoft.Graph.Authentication is not causing failure on installing.
=> Remove MS Graph 2.0 from GitHub Action, Run PowerShell Tests

baselines/exo.md
Adds the rationales to the EXO baseline.
Closes #434.
Copied the rationales into Word to catch obvious typos.
=> Add EXO rationales

Rego/AADConfig.rego, Testing/Unit/Rego/AAD/AADConfig_07_test.rego, sample-config-files/aad-config.yaml
- Remove the checks for the PIM settings "Allow permanent active assignment" and "Expire active assignments after 15 days".
- Replace those checks with code that examines if there are any permanent Active assignments. If there are, we show a Fail unless those assignments are in a config file exclusion.
- Also show a list of the roles currently "permanently" assigned to privileged roles. We currently hide this information which makes it harder for admins because they have to go look for it.
Code updated to match policy update in the baseline document
Closing #257 
- Unit tests
- Running against G5 test tenant
=> Update ScubaGear code for AAD baseline policy 7.4

baselines/teams.md
Teams baseline changes based on the comment matrix from pilots and internal test-based feedback.
Main changes include:
Reformat the baseline document with new structure and policy identifiers
Reorder couple policies (2 and 3) 
Refine and update policy statements (to remove any ambiguity) based on pilot feedback. 
Update implementation steps for many of policies 
closes #241 
closes #260 
closes #267 
closes #268 
closes #279 
closes #363 
closes #383
Walked through Teams admin center for each policy to confirm implementation steps
Cross-check comment matrix to ensure comments were addressed
Review the changes with another team member.
=> Teams baseline update based on the pilot feedback and internal testing

baselines/defender.md
Update the Defender baseline markdown to use the latest format and style as well as add rationales for the remaining policy items that are currently listed as TODO.
The current version of the Defender baseline has been reworked to use major formatting points like policy IDs and groups, but some of the smaller format and style changes are still lacking.  Additionally, the previously existing policies do not yet have rationales associated with each policy item.  Policy items will be updated to add those rationales to remove TODO placeholders.
Closes #246
Closes #427 
Confirm that the Defender related markdown checks in the GitHub action pass.
Compare the Defender baseline to the format example document.
=> Update Defender format and rationales

baselines/exo.md
This PR is designed to facilitate a formal review of the revised Exchange Onlinebaseline from CISA SCuBA principals and the Scuba development team. Following this review the baseline should be in a state for sending to the CISA agency formal review process.
A broad review by both the development team SMEs and the CISA SCuBA principals ensures a high quality update in line with agency goals and consistent policy format and styling.
=> Formal internal review of Exchange Online baseline

baselines/powerplatform.md
This PR is designed to facilitate a formal review of the revised Power Platform baseline from CISA SCuBA principals and the Scuba development team. Following this review the baseline should be in a state for sending to the CISA agency formal review process.
A broad review by both the development team SMEs and the CISA SCuBA principals ensures a high quality update in line with agency goals and consistent policy format and styling.
=> Formal internal review of Power Platform baseline

baselines/defender.md
Updating the front-matter and acknowledgements to the  Defender SCB to match language approved by the CISA Front office. Also added the HTML formatting for criticality to support new field in report. 
Changes are required to ensure consistency across SCBs for the approved front-matter and acknowledgements. Criticality HTML is added to support new report field and supporting automation.  
#471 
#341 
=> Update front matter, acknowledgements and criticality for Defender

baselines/teams.md
Updating the front-matter and acknowledgements to the AAD SCB to match language approved by the CISA Front office. Also added the html formatting for criticality to support new field in report. Also updated the links to defender now that formal review is finished. 
Changes are required to ensure consistency across SCBs for the approved front-matter and acknowledgements. Criticality HTML is added to support new report field and supporting automation.  Links to defender to align with policies that can be "passed" via defender. 
#471 
#341 
#435 
=> Update front matter, acknowledgements, criticality, and links to Defender for Teams Baseline

baselines/sharepoint.md
This PR is designed to facilitate a formal review of the revised Sharepoint / OneDrive baseline from CISA Scuba principals and the Scuba development team. Following this review the baseline should be in a state for sending to the CISA agency formal review process.
We have active development issues against this baseline at the moment. If any changes occur during this baseline review which materially affect the ScubaGear code, it may require a notification to the affected developers.
=> formal internal review of Sharepoint / OneDrive baseline

baselines/defender.md, baselines/exo.md
Microsoft noted in a recent [blog post](https://www.microsoft.com/en-us/security/blog/2023/07/19/expanding-cloud-logging-to-give-customers-deeper-security-visibility/) that they are expanding auditing. The change is meant to add a notation in related baseline audit policies to inform readers about the upcoming changes and likely update to baseline policies after the changes by Microsoft are complete.
The additional audit events previously requiring Purview (Premium) will now only require it if Purview is used for 1 year audit retention (since Standard only supports up to 180 days). If Purview is not used retention for 1 year (say another storage medium or service is used), then Premium licensing is not required.
Letting agencies know of these upcoming changes and the impact on baseline …
=> Update M365 Audit Policy Language in baselines

baselines/defender.md
This PR updates the Microsoft Defender Secure Configuration Baseline to include grammatical, formatting, and other style and consistency related updates based on a review from the team technical editor.  Updates have been taken from a marked up version and added back into the markdown.
This change ensures the highest quality and clarity of the wording used in the baseline to make it easier to read for users.
Closes #512
Test was to review the technical editor comments and suggestions and validate that the recommendations were consistent with the baseline technical language and improved the quality of the document.
=> Integrate technical editor feedback into Defender baseline

baselines/exo.md
This PR updates the Exchange Online Secure Configuration Baseline to include grammatical, formatting, and other style and consistency related updates based on a review from the team technical editor.  Updates have been taken from a marked up version and added back into the markdown.
This change ensures the highest quality and clarity of the wording used in the baseline to make it easier to read for users.
Closes #485
Test was to review the technical editor comments and suggestions and validate that the recommendations were consistent with the baseline technical language and improved the quality of the document.
=> Integrate technical editor feedback into Exchange baseline

Testing/Unit/PowerShell/CreateReport/Import-SecureBaseline.Tests.ps1, baselines/aad.md
Updated aad.md to remove extra line after Policy Id 7.3v1 and before description.  
Also fixed Sharepoint policy count in unit test so it passes.  
Closes #529 
Fix aad.md so Scuba executes properly for aad, et.al.
- Execute unit test with no errors
- Execute ScubaGear with aad in product list. 
=> HOTFIX:  aad.md is malformed

baselines/powerbi.md
This PR is designed to facilitate a formal review of the revised PowerBI baseline from CISA SCuBA principals and the Scuba development team. Following this review the baseline should be in a state for sending to the CISA agency formal review process.
A broad review by both the development team SMEs and the CISA SCuBA principals ensures a high quality update in line with agency goals and consistent policy format and styling.
=> Formal internal review of PowerBI baseline

baselines/sharepoint.md
This PR updates the SharePoint/OneDrive Secure Configuration Baseline to include grammatical, formatting, and other style and consistency related updates based on a review from the team technical editor.  Updates have been taken from a marked up version and added back into the markdown.
This change ensures the highest quality and clarity of the wording used in the baseline to make it easier to read for users.
Closes #510 
Test was to review the technical editor comments and suggestions and validate that the recommendations were consistent with the baseline technical language and improved the quality of the document.
=> Update sharepoint.md with tech editor feedback

baselines/powerplatform.md
This PR updates the Power Platform Secure Configuration Baseline to include grammatical, formatting, and other style and consistency related updates based on a review from the team technical editor.  Updates have been taken from a marked up version and added back into the markdown.
This change ensures the highest quality and clarity of the wording used in the baseline to make it easier to read for users.
Closes #509 
Test was to review the technical editor comments and suggestions and validate that the recommendations were consistent with the baseline technical language and improved the quality of the document.
=> Update powerplatform.md with tech editor feedback

baselines/teams.md
Teams baseline document has been updated based on tech editor feedback. The main changes are in Section 7 (Malware Scanning) where section intro has been updated. In addition, there were a few grammatical and stylistic edits throughout the document. 
The tech-editor feedback is to make the baseline document consistent with other baselines and make any suggestions/edits for grammar and style. Most the feedback has been accepted with a few exceptions. The tech editor provided word document has more details. 
N/A
=> Integrate technical editor feedback into teams baseline

Rego/AADConfig.rego, Testing/Unit/Rego/AAD/AADConfig_03_test.rego
Update MS.AAD.3.6v1 to check for for Phishing Resistent MFA.  Was just checking MFA.
Closes #543 
Policy was updated to use Phishing Resistent MFA instead of just MFA.
Unit tests updated 
All MS.AAD.3.6v1 Unit test pass
Run Scuba - Policy will fails due to "Phishing Resistant" not implemented. 
Run Invoke-Cached Run with appropraite input to pass.
=> Update MS.AAD.3.6v1 to check for Phishing Resistant MFA 

Rego/DefenderConfig.rego, Rego/Utils/DefenderUtils.rego, Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego, sample-config-files/defender-config.yaml
Check that sensitive users indicated in the config are protected from impersonation in the standard & strict policies.
Defender 2.1 specifies that "sensitive users" should be added to impersonation protection in standard & strict policies. After we have config support for this, we can verify the correct users are added.
- Unit Tests
=> Defender 2.1 Check Config for Sensitive Users

Rego/DefenderConfig.rego, Rego/Utils/DefenderUtils.rego, Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego, sample-config-files/defender-config.yaml
Assert that frequent partner domains are added to impersonation protection in both the standard and strict preset policies.
Closing #490 
Defender 2.3 specifies that "frequent partners" should be added to the strict preset EOP policy. By allowing the users to specify these in the config file, we can verify the correct domains are added.
-  Unit Testing
=> Add frequent partners to config file for Defender 2.3

baselines/powerbi.md
PowerBI baseline document has been updated based on tech editor feedback. The main changes are all grammatical and stylistic edits throughout the document. 
The tech-editor feedback is to make the baseline document consistent with other baselines and make any suggestions/edits for grammar and style. Most the feedback has been accepted with a few exceptions. The tech editor provided word document has more details. 
N/A
=> Update powerbi.md to align with tech editor comments

Testing/RunUnitTests.ps1, Testing/Unit/PowerShell/RunRego/Run-Rego.Tests.ps1
Removes old OneDrive unit test to `Invoke-RunRego` and `Testing\runUnitTests.ps1`.  The OneDrive rego file was removed after its tests were merged into the SharePoint rego file.  SharePoint rego testing is still present, so there is no loss of coverage.
Since the OneDrive.rego file was removed, it was causing this unit testing to fail.  Since this test is part of the Run-PowerShell-Tests GitHub action, it caused pipelines to always fail due to the error.  This update fixes the error allowing pipelines to pass or fail appropriately.  It also will prevent errors when manually running `Testing\runUnitTests.ps1`.
Closes #577
Closes #580 
Resolves previously failing test run.
Also resolves previously failing run of runUnitTests.ps1.  Now runs without errors.
to reflect the …
=> Fix failing OneDrive unit tests

Rego/DefenderConfig.rego, Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego
The emerald version of the M365 Defender baseline includes significant updates to policies for data loss prevention.  As a result, the assessment code also needs to be updated.  
Major updates in this request include:
* Add SensitiveInfoPolicies test for 4.1 matching DLP policies
* Ensure 4.2/4.3/4.4 fail if 4.1 fails via custom error messages
* Fix bug where 4.3 would pass when action is `Block People Outside of Organization` rather than `Block Everyone`
* Update unit tests to note failure when 4.1 DLP policies not present
* Convert and add 4.3 and 4.4 unit tests
* Convert existing 4.5 and 4.6 not implemented unit tests to new format
All tests in the group are dependent on 4.1 passing such that a custom policy exists that contains at least the minimum sensitive info types (SSN, ITIN, and …
=> Update and fix MS.DEFENDER.4.3-4.6 for newest baseline

baselines/exo.md
Single line change to the Exchange Online Secure Configuration Baseline.  The policy MS.EXO.5.1v1, notes to disable SMTP AUTH by default. However, it does allow for enabling on a per-mailbox basis if required to support legacy clients. The per-mailbox implementation instructions do not make it clear that admins do NOT need to implement this unless there is a clear requirement for a specific mailbox to do so. Update the lead-in for the implementation instructions to make this clear.
Updating the instructions will make it easier for readers to understand that this is an exception and not required to be consistent with secure configuration by default.
Closes #554 
Run automated tests to ensure markdown update is syntactically correct.
=> Clarify MS.EXO.5.1v1 implementation instructions for per mailbox exception

Testing/Unit/Rego/Teams/TeamsConfig_01-test.rego
Closes #612 
Correct report details match on teams unit test case.
Expect unit test case to all pass 
Executed unit test for teams 
=> Correct unit test case for teams 

Rego/SharepointConfig.rego
Correct logic for MS.SHAREPOINT1.4v1
Closes #610 
Use case when both SharingCapability and RequireAcceptingAccountMatchInvitedAccount are good fails policy. 
Verify policy passes with both SharingCapability disabled and RequireAcceptingAccountMatchInvitedAccount true. 
=> Share point1.4v1 issue

Testing/Functional/Products/TestPlans/exo.testplan.yaml
Update the Exchange automated test plan YAML configuration so that the `dkim_config` fields use `Domain` rather than `domain` in all tests as the capitalized version is the proper field name and the code is case sensitive.
Fixing this issue ensures that the automated testing properly checks the compliant case for MS.EXO.3.1.
Closes #617 
Ran EXO automated test plan configuration after changes to the code to verify that the previously failing test case now properly passes as expected.
Example of successful test run for MS.EXO.3.1 after the changes made in this branch.
=> Fix Exchange test plan failing for DKIM compliant test

PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/ScubaGear.psd1, README.md
Latest ScubaGear release requires bumping the module version from 0.3.0 to 1.0.0 and the baseline version from 0.1 to 1.
New releases require an updated version to differentiate both the baseline and module differences.
Closes #450 
Run `Invoke-Scuba` to see resulting reports with updated versions.
Summary HTML report page reports ScubaGear as v1.0.0
Individual product HTML report shows Module Version 1.0.0 and Baseline Version 1.
README.md shows installation bundle with 1-0-0 version
=> Bump ScubaGear versions for upcoming release

baselines/defender.md
This PR updates the implementation steps for the policy MS.DEFENDER.4.4v1 - the implementation steps are explained in 4.1v1 section. A new step 19 is added to correctly implement user notifications. Additional details are in issue #603 
Closes #603 
No code change. Defender baseline document update. Check the implementation steps provided for policy 4.x.
=> Update defender policy 4.4 implementation steps

.github/workflows/run_opa_tests.yaml
Remove GitHub action configuration that targeted the emerald branch now that emerald has been merged.
The emerald branch was used for development on the last release cycle.  Now that the branch has been merged to main, there is no longer active development on that branch and the tests no longer need to be run there.  Cleaning up the configuration is good to prevent bit rot over time.
Closes #362 
The only test is to ensure that the run_opa_tests GitHub action still works on other branches as intended. 
=> Remove emerald branch from OPA test action

.gitignore
Added DS_Store.
Prevents Mac-specific files from getting into repo.
n/a
=> Prevents DS_Store files from getting into the repo

.github/workflows/run_psscriptanalyzer.yaml
Improved name of step in GitHub Action workflow.
Reduces confusion.
n/a
=> Updated step name

baselines/exo.md
This update includes the following changes to the M365 Exchange Security Configuration Baseline:
- Changes to improve overall consistency of format and language throughout
- Grammar and spelling fixes
- Language and verbiage updates for increased reader clarity
The updates included further refine and improve the overall readability and clarity of the baseline document.  The result should be a baseline that is easier to interpret and use as a reference for M365 tenant administrators.
Closes #534 
- Compare the separately provided Word version with track changes of the Exchange …
=> Integrate review feedback into Exchange baseline

baselines/powerplatform.md
This update includes the following changes to the Power Platform security configuration baseline:
- Changes to improve overall consistency of format and language throughout
- Grammar and spelling fixes
- Language and verbiage updates for increased reader clarity
The updates included further refine and improve the overall readability and clarity of the baseline document. The result should be a baseline that is easier to interpret and use as a reference for M365 tenant administrators.
Closes #535  
Compare the separately provided Word version with track changes of the Power …
=> Integrate review feedback into Power Platform baseline

PowerShell/ScubaGear/Modules/Connection/ConnectHelpers.psm1, PowerShell/ScubaGear/RequiredVersions.ps1
The updates in this request do the following:
* Disables the remote powershell deprecation banner when calling `Connect-IPPSSession`
* Updates the minimum ExchangeOnlineManagement module version from v3.1.0 to v3.2.0
The ExchangeOnlineManagement PowerShell module used by ScubaGear includes the `Connect-IPPSSession` cmdlet which, by default, displays a warning banner message about remote PowerShell being deprecated.  While useful for developers, it does not help ScubaGear users.  The goal of this update was to suppress the message.  This can be done by adding the `ShowBanner:$false` parameter when making the cmdlet call.  This parameter, however, was only added in v3.2.0.  That is why this update also increases the minimum required version in ScubaGear from v3.1.0 to v.3.2.0.
Closes #687 …
=> Disable RPS deprecation banner

baselines/powerbi.md
Added the html formatting for criticality to support new field in report for future proofing and consistency to match other baselines.
Criticality HTML is added to support new report field and supporting automation.  
Closes #689
=> Added criticality to Power BI Markdown

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1, PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1
- Add `-UseBasicParsing` switch to our `Invoke-WebRequest` calls so that ScubaGear can run with containers. 
Closes #305
Tested on E5, G3, G5, GCC High Tenants.
=> Add -UseBasicParsing to Invoke-WebRequest to support Servercore Windows images

.github/workflows/run_markdown_check.yaml, .github/workflows/run_opa_tests.yaml, .github/workflows/run_powershell_tests.yaml, .github/workflows/run_psscriptanalyzer.yaml, .github/workflows/run_release.yaml, .github/workflows/run_smoke_test.yaml
Updated version of a GitHub action.
Updating to current version reduces security threat vectors.
The GitHub Action ran, and the code was checked out.  Success!
=> updated checkout action version

Testing/Functional/SmokeTest/SmokeTestUtils.ps1
Removes un-needed work-around for loading correct PnP version. Now handled by SetUp.ps1 directly.  
closes #724 
Desires single point for controlling required modules. 
Ran smoke test [workflow ](https://github.com/cisagov/ScubaGear/actions/runs/7144921437/job/19459530346)w/o work-around successfully
=> Remove PnP work-around for Smoke Test

baselines/aad.md
Modified the AAD baseline markdown file to align with the changes received from CISA's final review.
=> Integrate OCC review feedback into the AAD baseline

baselines/defender.md
This update includes the following changes to the Defender security configuration baseline:
- Reorder and clarify intro language on use of security tool
- Add more intro rider language
- Remove acknowledgements section
- Reorder and clarify notes on 1.2 and 1.3
- Clarify DLP and sensitive info relationship language
- Minor grammar changes throughout
This update integrates feedback from OCC into the baselines to improve overall consistency of language and inclusion of agency standard disclaimers.
Closes #712 
Open the associated branch and view both the raw and rendered versions …
=>  Integrate OCC review feedback into the Defender baseline

baselines/powerbi.md
This update includes the following changes to the PowerBI security configuration baseline:
- Changes to improve overall consistency of format and language throughout
- Language and verbiage updates for increased reader clarity
The updates included further refine and improve the overall readability and clarity of the baseline document. The result should be a baseline that is easier to interpret and use as a reference for M365 tenant administrators.
Closes #714
Compare the separately provided Word version with track changes of the PowerBI baseline document with the changes in the …
=> Integrate OCC review feedback into the Power Bi baseline

baselines/exo.md
This update includes the following changes to the EXO security configuration baseline:
- Changes to improve overall consistency of format and language throughout
- Grammar and spelling fixes
- Language and verbiage updates for increased reader clarity
The updates included further refine and improve the overall readability and clarity of the baseline document. The result should be a baseline that is easier to interpret and use as a reference for M365 tenant administrators.
Closes #713
Compare the separately provided Word version with track changes of the EXO baseline document …
=> Integrate OCC review feedback into EXO baseline

Rego/PowerPlatformConfig.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_01_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_02_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_03_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_04_test.rego, Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_05_test.rego
=> Refactor Power Platform

Rego/TeamsConfig.rego, Testing/Unit/Rego/Teams/TeamsConfig_01_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_02_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_03_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_04_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_05_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_06_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_07_test.rego, Testing/Unit/Rego/Teams/TeamsConfig_08_test.rego
=> Refactor Teams Rego Code

Testing/Functional/SmokeTest/UpdateSelenium.ps1
Refactored smoke test to attempt to get good download multiple time.  
closes #726 
Developer waste time troubleshooting failed download instead of application code. 
Executed smoke test successfully
=> Smoke test periodically fails

Rego/AADConfig.rego, Testing/Unit/Rego/AAD/AADConfig_01_test.rego, Testing/Unit/Rego/AAD/AADConfig_02_test.rego, Testing/Unit/Rego/AAD/AADConfig_03_test.rego, Testing/Unit/Rego/AAD/AADConfig_04_test.rego, Testing/Unit/Rego/AAD/AADConfig_05_test.rego, Testing/Unit/Rego/AAD/AADConfig_06_test.rego, Testing/Unit/Rego/AAD/AADConfig_07_test.rego, Testing/Unit/Rego/AAD/AADConfig_08_test.rego
=> Refactor AAD Rego Code

Rego/DefenderConfig.rego, Testing/Unit/Rego/Defender/DefenderConfig_01_test.rego, Testing/Unit/Rego/Defender/DefenderConfig_02_test.rego, Testing/Unit/Rego/Defender/DefenderConfig_03_test.rego, Testing/Unit/Rego/Defender/DefenderConfig_04_test.rego, Testing/Unit/Rego/Defender/DefenderConfig_05_test.rego, Testing/Unit/Rego/Defender/DefenderConfig_06_test.rego
=> Refactor Defender Rego Code

.github/workflows/run_linter_powershell.yaml, .github/workflows/run_linter_yaml.yaml, Testing/Linting/MegaLinter/.mega-linter-powershell.yml, Testing/Linting/MegaLinter/.mega-linter-yaml.yml, Testing/Linting/MegaLinter/.yamllint.yml, Testing/Linting/MegaLinter/README.md
Added 2 new workflows, both of which use MegaLinter to lint.  One lints PowerShell and the other YAML.
Linting keeps files consistent.
Closes #742 
Closes #743 
Ran the pipelines and checked the results.
=> Add PowerShell and YAML linters

.github/workflows/run_functional_product_tests.yaml, .github/workflows/run_publish_package.yaml, .github/workflows/run_smoke_test.yaml, .gitignore, Testing/Functional/BuildTest/ModuleBuild.Tests.ps1, Testing/Functional/Products/SetupFunctionalProductTesting.md, Testing/Functional/Products/Tests/CallProductTests.ps1, Testing/Functional/Products/Tests/RemoveOutputFolders.ps1, utils/DeployUtils.ps1
Focus is on creating a private package repository to publish a catalog signed ScubaGear module for a nightly build.
A nighly build/test of the ScubaGear module will help uncover any issues early that might impact an official production publish to PowerShell Gallery. 
closes #672 
closes #674 
closes #675 
closes #676 
The github workflow, run_publish_package, create a repo, build the module (i.e., update manifest, sign), publishes to repo, runs test on "Find-Module", installs/imports module from repo and test with simple "Invoke-Scuba -Version"
NOTE: AT this time the published module is not expected to be able to test actual products.  #677 refactors ScubaGear to work when installed as a module.
=> Add workflow to publish module for scubagear to test package repository

.github/pull_request_template.md
Adds a new template for pull requests to the ScubaGear project repository.  
The new template is crafted to better align to the project's current development and release process.  Having additional and appropriate checklist items helps developers and contributors ensure that the pull request contains the necessary information for reviewers and has meet the correct criteria for inclusion into the project.
Closes #57 
The template is basic markdown and was tested using a Markdown rendering engine (VSCode extension).  Additionally, the new template was used as the basis for this pull request itself.
in code comments
to reflect the changes in this PR
=> Add project-specific pull request template

OPA.ps1
OPA.ps1 should exit with a success/failure, instead results in a runtime error when exiting with failure.
fixed spelling error `SilientlyContinue -> SilentlyContinue`
closing #768 
=> Fix debug preference error in OPA.ps1

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
- Remove the hard-dependency on IPv4 for the DoH call
- Adjust the DoH logic so that DoH calls are not made when DoH is blocked
Closes #737. Additionally, while working #737, made the following realization: when DoH is not available, a lot of time will be wasted on DoH calls. For example, if DoH calls are blocked by a proxy, it could take several seconds before an exception is thrown. Then it will retry the query. And it will do this for each domain name. On our G5 testing tenant, that results in 24 DoH calls, so that adds up. Now imagine the latency that would create for a large organization with many more domains...a change was needed. The change: when it becomes evident that DoH will be needed, first test to see if DoH is available. If it's not, skip all subsequent attempts to make a …
=> Enhance DoH Logic

.github/workflows/run_publish_package.yaml, .github/workflows/run_release.yaml, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-ReportCreation.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-RunCached.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1, sample-config-files/aad-config.yaml, utils/DeployUtils.ps1
Refactor run release workflow to use azure key vault housed certificate.  Instead of using locally installed certificate the workflow uses a certificate housed in an Azure Key Vault.  
closes #780 
This is foundational work to support transition to HSM based code siging certificate.  
Execute workflow and verify release is generated.
Performs a "quick check" to download release, install, and execute. 
=> Refactor run release workflow to use azure key vault housed certificate

PowerShell/ScubaGear/Testing/Unit/PowerShell/Utils/DeployUtils.Tests.ps1, Testing/Functional/BuildTest/ModuleBuild.Tests.ps1, utils/DeployUtils.ps1
Insert tags into the ScubaGear manifest so when published to PSGallery it can be discovered by tag search. 
This is a Microsoft best practice when publishing a module to a gallery. 
closes #694 
=> Insert Tags into Module for Discovery 

.github/workflows/run_functional_product_tests.yaml, Testing/Functional/Products/Tests/CallProductTests.ps1
This PR adds Teams to the nightly tests (along with SharePoint).  Several small configuration changes enable multiple products to be supported, not just one.
This closes:  https://github.com/cisagov/ScubaGear/issues/731
The nightly functional tests provide developers with information about product changes that have created new and unexpected issues.  As functional testing is time consuming, these tests are run nightly instead of on push.
These tests are implemented as a GitHub Action workflow, so I ran the workflow.
Note that the Team tests are currently failing due to an issue in Teams test plans.  This PR, however, is functioning as intended.
The remaining nightly tests will be finished via this issue:  https://github.com/cisagov/ScubaGear/issues/824
Use `Rebase branch` button below or …
=> Improve nightly functional tests

PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADConditionalAccessHelper.psm1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Export-Caps.Tests.ps1
Add logic to check for terms of use in the conditional access table generation.
Closes #454.
Tested on E5, G5, G3, and GCCHigh. When testing on the G5 tenant, make note of the "Terms of Use Policy" CAP I added to the tenant.
=> Add terms of use handling to CAP table

PowerShell/ScubaGear/baselines/exo.md
The Exchange Online baseline has a small policy ID reference error in the MS.EXO.17 implementation instructions section.  Rather than referencing MS.EXO.17.2v1 and MS.EXO.17.3v1, the version is incremented instead.  This PR updates the Exchange Online baseline to correct the policy reference IDs to the appropriate values.
Baseline documents should be clear and references should be correct to prevent user confusion or errors in interpreting guidance.
Closes #861 
Old, incorrect implementation section
Newly updated, correct implementation section policy references
=> Fix MS.EXO.17 implementation instruction policy ID refs

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1, PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html, PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html, PowerShell/ScubaGear/Modules/Orchestrator.psm1
Resolves the issue of HTML report links to GitHub main branch baselines rather than versioned baselines on both parent report and individual reports by executing a find and replace using { BASELINE_URL }  on report html templates.
closes #654 
Tested that parent report links to versioned baselines
Tested individual report links to versioned baseline of the specific baseline name
=> HTML Report Links to Version Baselines

PowerShell/ScubaGear/baselines/aad.md
Updates the AAD baseline document section 7 privileged user policy instructions to include steps for organizations that are using PIM for Groups. For a description of the changes made refer to https://github.com/cisagov/ScubaGear/issues/376#issuecomment-1901021877.
Closes #376
Closes #797 
=> Update AAD baseline to include PIM for Groups (the return of)

.github/workflows/run_release.yaml
Updated release build workflow to use new production code signing certificate.
Closes #790 
ScubaGear code needs to be signed to be trusted. 
Created a release and verified file signed. 
=> Update release to use production code signing certificate

PowerShell/ScubaGear/ScubaGear.psd1, README.md
Prepare for new ScubaGear release by bumping the version from 1.0.0 to 1.1.0. Clarify need for any baseline version changes for this release.
New releases require an updated version to differentiate both the baseline and module differences.
Closes #851 
Run `Invoke-Scuba` to see resulting reports with updated versions.
Summary Report Footer
Individual report header
Baseline links in individual reports port to correct tag version
Note:  Full URL will change due to folder changes, test result focuses on version tag only as outstanding PR will resolve path issue.
=> Version bump to 1.1.0

PowerShell/ScubaGear/baselines/powerbi.md
Add TLP:CLEAR information note to PowerBI documentation
closes #817 
Check that the introduction section of the PowerBI baseline for TLP:CLEAR information note
=> add TLP:CLEAR information note to powerbi baseline 

OPA.ps1, README.md, SetUp.ps1
ScubaGear supports up to 0.59.0. And the most recent OPA version is 0.61.0 now. Add latest support to the tool.
Adding the 0.60.0 and 0.61.0 version to the list of acceptable versions in the OPA.ps1 install script
Updating the default install version to 0.61.0
closes #777 
Run the OPA.ps1 or SetUp.ps1 to ensure it install the latest version of OPA (0.61.0)
Run .\Testing\RunUnitTests.ps1 to ensure all test still passes. 
=> update supported opa versions to 0.61

.github/workflows/run_linter_powershell.yaml, .github/workflows/run_linter_yaml.yaml, .github/workflows/run_markdown_check.yaml, .github/workflows/run_opa_tests.yaml, .github/workflows/run_pipeline.yaml, .github/workflows/run_powershell_tests.yaml, PowerShell/ScubaGear/RequiredVersions.ps1
This PR adds a new workflow that is the start of ScubaGear's CI/CD pipeline.  To date, SG has used a variety of workflows to test various aspect of the codebase, but these have not been brought together in a complete, coherent pipeline.  This PR is the start of that pipeline.
This PR:
- adds a new CI/CD pipeline that covers linting, syntax checking, and unit testing (other steps to be added later)
- modifies existing workflow so that they only run manually or when called by the pipeline
- enables the pipeline to reuse existing workflows without having to duplicate code (avoids DRY)
- checks to see what files have been changed since the last commit, and only runs checks for those file types that have changed
- allows a user to manually run the pipeline and execute all step regardless of …
=> Create initial software dev pipeline

PowerShell/ScubaGear/ScubaGear.psd1, README.md
Bump the version from v1.1.0 to v1.1.1.
Since the hotfix release was added, the main branch needs to have its version bumped to match the latest hotfix.
Run ScubaGear via `Invoke-Scuba -Version` and `Invoke-Scuba` to show that both the command line and HTML report shows the correct updated version v1.1.1.
=> Version bump main to v1.1.1

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
The "if" is no longer needed. There were some cases where this actually caused bugs in the report output. It's been so long though that those bugs may or may not be able to be replicated at this point. But as a defensive measure we should remove the if that's no longer needed. 
- Removal of the if statement is implemented in this change.
- closes #145 
1. Generate report before if removal using  same reproduction code in issue:
```
.\Testing\Functional\RegoCachedProviderTesting.ps1 -ProductNames aad -LogIn $true -ExportProvider $true -Quiet $false
.\Testing\Functional\RegoCachedProviderTesting.ps1 -ProductNames aad -LogIn $false -ExportProvider $false -Quiet $false
.\Testing\Functional\RegoCachedProviderTesting.ps1 -ProductNames aad,teams -LogIn $false -ExportProvider $false -Quiet $false …
```
=> Force enhanced error handling to all updated providers

.github/workflows/run_publish_package.yaml, PowerShell/ScubaGear/Testing/Unit/PowerShell/Utils/DeployUtils.Tests.ps1, utils/DeployUtils.ps1
Adds support to specify a published module is a prerelease version (e.g., 1.0.0-alpha)
Closes #865 
Scuba Gear may need to publish prereleases that are not generally available to the public. 
Ran unit test, passed 
Run run_publish_package,yaml workflow.  All test passed. 
=> Support prerelease publishing of modules to package repository

README.md
Follow on to existing hotfix version bump.  This change updates the README to ensure latest version v1.1.1 is used for the example release file name.
Closes #925 
Review contents of [Download latest release](https://github.com/cisagov/ScubaGear/blob/2bdc72a570b70e37e18ebd00e304d0ec655fc782/README.md#download-the-latest-release) section of the README.md file.
=> Update version in release filename to 1-1-1

PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1
Added a ScubaDefault method to ScubaConfig class. 
closes #767 
The app had several entry points with potential for different default values (e.g., OPA Path).  This enhancement gives us a single location for Scuba default values that can be used through out the app.  
- Executed PowerShell unit test, all passed. 
- Executed Invoke-Scuba against a tenant, expected results. 
=> Add app level defaults

PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Get-ServicePrincipalParams.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Connection.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Orchestrator/Invoke-Scuba.Tests.ps1
closes #169
Added additional unit test to cover passing/processing of service principal parameters.
Unit test cases were added to increase coverage. 
Executed PowerShell unit test, all passed
=> Add PowerShell unit test cases for when service principals are passed into scubagear

PowerShell/ScubaGear/baselines/aad.md
Modify the AAD baseline document instructions for policies 7.6 through 7.9 to incorporate PIM for Groups. There is a coding issue that is currently in the works that aligns with these changes as well.
Closes #920 
=> add PIM for Groups to AAD baseline instructions for 7.6 through 7.9

PowerShell/ScubaGear/Rego/SharepointConfig.rego, PowerShell/ScubaGear/Rego/TeamsConfig.rego
SharePoint and Teams had mis-alignment between code and secure baseline document for policy criticality.  Modified code to align with document.
closes #949 
This is require to generate the correct criticality in the report. 
Executed SharePoint and Teams to verify modified alignments display properly. 
Manually review all baseline documents against code to check for other criticality issues.
SharePoint: 1.1, 1.2, 3.1, 3.2, 3.3
Teams: 6.2
=> Aligned baseline policies criticality between code and document

PowerShell/ScubaGear/RequiredVersions.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1
Updated required version info to specify MS Graph module up to 2.15.xxx,
closes #930 
It is important to keep dependencies up to date to get new features and security fixes. 
- Ran Import-Module without acceptable versions of MS Graph. Was prompted to Initialize-SCuBA
- Initialize-SCuBA to get required versions of MS Graph
- Invoked-SCUBA against tenants to verify functionality
=> Re-pin MS Graph to latest major/minor (i.e., 2.15.xx) version

.github/workflows/publish_package.yaml
Change to not look in private package repo and PSGallery repo.  
closes #973 
We cannot predict how many versions of ScubaGear will be in Public repo.  So for testing we only want to consider the private repo. 
- Manually trigger publish private package 
=> Specify Repo to query in Public Private Package workflow

PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_07_test.rego
Modified the 4 AAD unit tests that were not working - shortest description ever -- !
Closes #1018 
Things should not be broken.
=> Fix the Handful of AAD unit tests that are broken

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
- Uncenters the text in the individual report tables
Closes #1030
Run ScubaGear look at tables. 
Before
After
Probably not best example to show but the other rows are back to their left aligned selves
=> Uncenter the text in the HTML report

.github/workflows/run_pipeline.yaml, .github/workflows/run_secret_scan.yaml, .github/workflows/unit_test_powershell.yaml
This PR adds the GitLeaks workflow to our CI/CD pipeline.
Closes #978 
GitHub has a builtin secret scanner, but we wanted a second tool to avoid "putting all of our eggs in one basket."  I had researched and tested various scanners and found GitLeaks to be a good choice.  In a previous issue, I had created a workflow for GitLeaks, so in this issue I was simply connecting it to our pipeline.
Ran the CI/CD pipeline.
Verified that GitLeaks was running and found no errors.
=> Add GitLeaks to CI/CD Pipeline

Testing/Functional/Products/TestPlans/aad.testplan.yaml
AAD functional test 5.3 was failing the compliant case in the G5 tenant and not other ones. Turns out that the functional test code was incorrectly producing a duplicate EnableAdminConsentRequests in the directory_settings JSON node which was throwing off the Rego policy check. I rectified this by changing the test to create a single EnableAdminConsentRequests field.
closes #1024 
Tested against the E5 and G5 tenants by manually running the functional tests for 5.3.
=> fixed functional test for AAD 5.3 so that it only produces a single EnableAdminConsentRequests field

Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml
AAD functional tests 7.4 & 7.5 were failing the non-compliant test cases when running in GitHub actions against the G5 and GCC high tenants. The root cause was the functional test cases hard coding the privileged_roles Assignments element [0] in the JSON array. That crashed in certain tenants so I modified the tests to create a JSON array that is deterministic and has a compliant and non-compliant Assignments element.
closes #1025 
I tested the GitHub actions Nightly Product Functional Tests to ensure that the G5 variant test plan worked against the G5 and GCC high tenants.
=> fixed AAD functional test failures for non-compliant tests 7.4 7.5 when running in GitHub actions

PowerShell/ScubaGear/baselines/sharepoint.md
Errors found in the sharepoint.md regarding comments in the file.
Found some typos in the sharepoint.md file where `` was duplicated erroneously.
Fixing documentation.
No code changes, only changed to the markdown.
=> Fixed documentation comments in sharepoint.md

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1
Update the AAD warning note at the beginning of the report to the new agreed upon text and add a link to the current CAP exclusions.
Closes #985 
User reported issue requesting more clear information about how the CAP exclusions affect the ScubaGear Policies
Run ScubaGear with AAD and make sure that the new note in AAD isn't causing any issues and that the link works in all cases.
=> Updating the CAP exclusion for AAD

PowerShell/ScubaGear/RequiredVersions.ps1
- Begin pinning the required ExchangeOnlineManagement PowerShell module version to a specific maximum minor version instead of a major version.
Closes #1115
- Run ScubaGear with` -ProductNames exo, defender` included.
- Currently passing for all the test tenants on my end for EXO v3.4
(https://github.com/cisagov/ScubaGear/blob/main/CONTENTSTYLEGUIDE.md).
=> Pin ExchangeOnlineManagement module version to < v3.5

PowerShell/ScubaGear/Modules/CreateReport/CreateReport.psm1, PowerShell/ScubaGear/Modules/CreateReport/IndividualReport/IndividualReport.html, PowerShell/ScubaGear/Modules/CreateReport/ParentReport/ParentReport.html, PowerShell/ScubaGear/Modules/CreateReport/scripts/ParentReport.js, PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js, PowerShell/ScubaGear/Modules/CreateReport/styles/ParentReportStyle.css, PowerShell/ScubaGear/Modules/CreateReport/styles/main.css
Improves usability of the HTML reports with a screen reader as well as keyboard navigation support. 
This PR closes the epic #1061 which addressed follow-up issues found after testing for 508/WCAG compliance. 
Closes #1061 
Closes #961 
Closes #972 
Closes #1047 
- Used [NVDA](https://www.nvaccess.org/download/) to test screen reader accessibility across parent and individual reports.
- Tab through headers, dark mode switch, links, as well as CAP table which has expand/collapse arrows for each row.  
- Zoom in/out of the page to see if font size adjusts.
=> Add accessibility improvements to the reports 

PowerShell/ScubaGear/Modules/Providers/ExportEXOProvider.psm1
Removed unnecessary line of code in EXOProvider
Closes #1150 
Run exo against all 3 tenants and it runs without any issues
=> Removed Extra Line of Code in EXO

PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointBaseConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_01_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_02_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_03_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego
Create central Jsons configs that can be pulled and modified slightly for each unit test
Closing #1109 
Reduce copy and paste errors and file size. Reduce the difficulty of writing unit tests and PRs. In the process of refactor, discovered false passing in unit tests, adding fix as closely related
=> Refactor SharePoint Unit test to pull from central Jsons

PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformBaseConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_01_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_02_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_03_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_05_test.rego
Create central Jsons configs that can be pulled and modified slightly for each unit test
Closing #1110 
Reduce copy and paste errors and file size. Reduce the difficulty of writing unit tests and PRs. In the process of refactor, discovered false passing in unit tests, adding fix as closely related
=> Refactor PowerPlatform Unit test to pull from central Jsons

PowerShell/ScubaGear/Rego/EXOConfig.rego, PowerShell/ScubaGear/Testing/Unit/PowerShell/CreateReport/CreateReportStubs/TestResults.json, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_02_test.rego, PowerShell/ScubaGear/baselines/exo.md, Testing/Functional/Products/TestPlans/exo.testplan.yaml
Update and revise MS.EXO.2.1v1 and MS.EXO.2.2v1 baseline policies. Revisions include: deletion of MS.EXO.2.1v1 in the markdown, renaming and updating the language of MS.EXO.2.2v1 in the markdown, updating the rego code to be consistent with markdown changes, updating unit tests and functional tests to align with rego code changes.   
closes #900
- Verify that EXO markdown baselines are updated to delete MS.EXO.2.1v1, rename MS.EXO.2.1v1.
- Execute EXO baseline on a tenant and confirm that control group 2 has a single test and that it is showing correct result
- Execute EXO unit tests and ensure that all tests are passing
- Execute EXO functional tests and ensure that all tests are passing
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to …
=> Revise SPF requirement policies of EXO baselines and update Rego code for the 2 updated policies

PowerShell/ScubaGear/baselines/exo.md
MS.EXO.14.4v1 is duplicated in the baseline markdown. Issue and PR opened to remove this duplication.
Change required to ensure only one instance of a baseline policy is found in the markdown.
Closes #1213 
N/A
=> Remove duplicated policy EXO.14.4v1

PowerShell/ScubaGear/Rego/AADConfig.rego, PowerShell/ScubaGear/Rego/Utils/AAD.rego, PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADBaseConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_06_test.rego, Testing/Functional/Products/TestPlans/aad.testplan.yaml
Modified the rule for MS.AAD.6.1 such that federated domains are excluded from the check. Only domains with AuthenticationType = "Managed" will be considered. 
That being said, detailed reporting is expanded to indicate to the user if federated domains are present. Users should refer to their identity provider on how to configure these domains in a federated context. 
Resolves #1080 
From .\Testing run 
```
.\RunUnitTests.ps1 -p aad -c 6
```
To run functional tests copy/paste into a PS script: 
```
$TestContainers = @() 
$TestContainers += New-PesterContainer -Path "Testing/Functional/Products" `
-Data @{ 
Thumbprint = "<thumbprint>"; 
TenantDomain = "<domain>"; 
TenantDisplayName = "<display-name>"; 
AppId = "<app-id>"; 
ProductName = "aad"; 
M365Environment = "gcc"
} 
$PesterConfig = @{ …
```
=> Modify MS.AAD.6.1 to account for federated domains

Testing/Functional/Products/Products.Tests.ps1, Testing/Functional/Products/TestPlans/aad.g5.testplan.yaml, Testing/Functional/Products/TestPlans/aad.testplan.yaml, Testing/Functional/Products/TestPlans/defender.testplan.yaml, Testing/Functional/Products/TestPlans/exo.testplan.yaml, Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml
Fixed the Functional Testing test plans that originally had the original naming convention, RunCached, to be aligned with the new non-generic cmdlet name, ScubaCached
Cached Functional Tests were failing, with this fix, they should pass.
Closes #1239
Run the Cached Functional Tests
=> Fixed Cached Functional Tests

PowerShell/ScubaGear/Rego/SharepointConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/Sharepoint/SharepointConfig_04_test.rego, PowerShell/ScubaGear/baselines/removedpolicies.md, PowerShell/ScubaGear/baselines/sharepoint.md, Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml, Testing/Functional/Products/TestPlans/sharepoint.spo.testplan.yaml
Removal of policy MS.SHAREPOINT.4.1v1 due to Microsoft's update to the classic admin center. This PR includes the baseline document updates that were approved in PR #1228 and adds the removal of the code references to ensure the changes are done in one PR. Previous baseline PR was to expedite the approval of the changes to submit to CISA faster. 
M365 option to enable and disable custom scripting for on personal sites (aka OneDrive) has been deprecated from the classic settings page within the SharePoint Admin Center. Since this capability has been removed the policy and implementation steps will also be removed from the SCBs and code to minimize confusion from users. Context of this change has also been added to the removedpolicies.md file.
Closes  #1227 (baseline issue)
Closes #1229 …
=> Remove MS.SHAREPOINT.4.1v1 policy and references (baseline and code)

PowerShell/ScubaGear/baselines/aad.md
This reference should be to on-prem Active Directory.  It was erroneously update in previous baseline update.
Fix a mistaken rename
Accuracy of the baseline.
Validate that updated baseline is well-formed.  Simple smoke test.
=> Fix erroneous AD -> Entra ID rename

Testing/Functional/Products/TestPlans/defender.g3.testplan.yaml, Testing/Functional/Products/TestPlans/defender.g5.testplan.yaml, Testing/Functional/Products/TestPlans/defender.testplan.yaml
Several of the Defender functional tests were failing due to issues with change timing and precondition tenant configuration commands.  This update:
- Adds the `-ErrorAction Continue` flag to all test PreCondition calls to `Enable-EOPProtectionPolicyRule` to prevent test failures if said policy rule is already enabled.
- Adds a filter to test preconditions that pull a user from the tenant Entra ID directory to ensure said user information is for a user with an email address in the tenant (not a guest)
- Changes the MS.DEFENDER.6.2v1 tests to use cached settings for testing to prevent failures due to delays in effective changes for audit settings and so as not to disable auditing in test tenants.
Additional issues with parallel execution of different Defender test plans in the tenant were …
=> Fix failing defender functional tests

PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOBaseConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_01_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_02_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_03_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_05_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_06_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_07_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_12_test.rego, PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_13_test.rego
Create central JSON config that can be pulled and modified slightly for each unit test
Closing #1111 
Reduce copy and paste errors and file size. Reduce the difficulty of writing unit tests and PRs
=> Reworked EXO Unit Tests to use 1 JSON

docs/execution/execution.md
This is a simple update to the docs to make the need to initialize clear.
Closes: #1263
=> Add initialize-scuba to execution page

PowerShell/ScubaGear/baselines/aad.md, PowerShell/ScubaGear/baselines/defender.md, PowerShell/ScubaGear/baselines/exo.md, PowerShell/ScubaGear/baselines/powerbi.md, PowerShell/ScubaGear/baselines/powerplatform.md, PowerShell/ScubaGear/baselines/sharepoint.md, PowerShell/ScubaGear/baselines/teams.md
PR to sync the grammatical and consistency of the language found in the Iceberg SCBs to adjudicate the comments left by the JCDC review team.
Closes #1291 
This work is needed to address the comments left by the JCDC in the consolidated change document to sync the markdowns with the change document going through CB publication review.
N/A
=> Update Iceburg SCBs to adjudicate comments made by JCDC during CB publication review

.github/workflows/test_production_function.yaml
Set a default value for the email input.
Closes:  #1389
Create a test repo to test the solution:  https://github.com/james-garriss/test-schedule-inputs/tree/main
=> Fix schedule bug in nightly functional tests

.github/pull_request_template.md
Added a demo checkbox so that any change medium or higher will have to have a formal demo showing code changes and functional changes.
=> Add demo requirement to PR template pre-approval checklist

PowerShell/ScubaGear/Testing/Unit/Rego/EXO/EXOConfig_04_test.rego
- Fix the Exchange unit tests that cause long lines warnings from Regal. 
Closes #1322 
- Reran the Exchange Unit Tests to see if anything broke. Nothing did.
=> Correct Exchange unit tests that triggered long lines Regal warnings

PowerShell/ScubaGear/baselines/aad.md, PowerShell/ScubaGear/baselines/defender.md
Updated the broken markdown links that were causing 404 errors. 
Closes #1341 
validate that the broken links listed in the issue have been updated and no 404 issues occur.
=> Update incorrect hyperlinks in SCB markdown

.github/workflows/test_production_function.yaml
The cron schedule for the functional test workflow was modified to run early in the morning Mon through Fri.
Closes: #1427 
Validated cron via online cron generator website.
As schedules only work on main, the final test will come after merging.
=> Update schedule for functional test workflow

Testing/Functional/Products/Products.Tests.ps1
The AAD functional tests are currently failing because the service principals table was added, so an additional block was added to the product.tests in order to mitigate the issue.
Closes #1564
Run the functional aad tests on all tenants to make sure they work. Check the workflow which is running functional tests on this branch to ensure it passes and there are no other issues running scubagear.
=> Update AAD functional tests for service principal table

PowerShell/ScubaGear/RequiredVersions.ps1
[RequiredVersions.ps1](https://github.com/cisagov/ScubaGear/blob/main/PowerShell/ScubaGear/RequiredVersions.ps1) references the same module twice. This PR removes the duplicate instance.
Closes #1589 
- Ran `Initialize-SCuBA` with no error
- Ran `Invoke-SCuBA` in interactivel/noninteractive with no error
- Ran [smoke test](https://github.com/cisagov/ScubaGear/actions/runs/13448021720/job/37577351117)
~- [ ] Unit tests added/updated to cover PowerShell and Rego changes.~
~- [ ] Functional tests added/updated to cover PowerShell and Rego changes.~
=> Remove duplicate ModuleName "Microsoft.Graph.Beta.Applications" from RequiredVersions.ps1

README.md
@schrolla noted that when viewing the readme on GitHub pages the ScubaGear logo is currently broken. This PR will removed the current absolute URL to accurately show up on GitHub pages.
change is required for the GitHub pages to show the ScubaGear logo.
closes issue #1575 
created a fork with the changes added to main and published to a new GitHub pages site.
link to GitHub pages site: https://ahuynhmitre.github.io/ScubaGearlogoupdate/
screenshot linked below.
=> Update README.md with relative rather than absolute URL for ScubaGear logo

Testing/Functional/Products/Products.Tests.ps1
Occasionally, Selenium fails to start its web server in a timely manner, causing some of the tests to fail.  This PR detects that failure and tries again.  This is not an absolute fix of the problem; that is, it solves the effect, not the cause.  I believe the real fix will happen based upon the outcome of #1525.
Closes:  #1338 
In "Files changed," it appears that I re-wrote this entire file; I did not.  The file was indented inconsistently, so I cleaned that up.  The only code changes were lines 274 to 282.
I ran the functional tests every morning and night and over the weekend for 2 weeks.  I never saw the error again.  
Reviewers cannot really test this for themselves unless they want to rerun this many times over the coming weeks.  (And if you do this, don't do it during the work …
=> Make sure that the Selenium server is ready

.github/workflows/run_smoke_test.yaml, Testing/Functional/SmokeTest/SmokeTestUtils.ps1, utils/workflow/Invoke-SmokeTests.ps1
This is part of epic #1402 which is about moving PowerShell code out of workflow into functions so they can be unit tested.  This issue moved the smoke test into a function, but didn't write unit tests for it, because smoke tests are themselves tests (duh).
Closes: #1488 
To verify that these tests are running, run the Smoke Test workflow on branch 1488.
=> Move smoke tests into a function

PowerShell/ScubaGear/baselines/powerplatform.md
Microsoft has added the note for Content Security Policy (CSP) only applies to environments using Dataverse. To match, the SCBs should also note this dependency as noted by an external user. 
Change required to match Microsoft documentation and address questions from the users of the tool and SCBs of this dependency.
Closes #1476 
N/A only change is in the SCBs and is a note in the policy
-->
=> Add note to MS.POWERPLATFORM.4.1v1 to highlight dataverse dependency 

.github/workflows/publish_private_package.yaml, .github/workflows/publish_public_package.yaml, Testing/workflow/Publish-ScubaGear.Tests.ps1, utils/workflow/Build-SignRelease.ps1, utils/workflow/Publish-ScubaGear.ps1
Some of the code in here has already been cleaned up.  I did the rest of it:
* Moved some code into a function.  
* Wrote a unit test.  
* Added two inline tests.
* Noted where other workflows should also use function.
Closes: #1581
To test the changes:
* Manually run the Functional Tests on branch 1581, but cancel them as soon as first step, Publish Package, is done.  Look at the results.  This step should be green.
* Manually run the Workflow Pipeline on branch 1581 and look at Workflow Unit Tests.  This step should also be green.
=> Move code for publish private package into functions and test

.github/workflows/run_update_opa.yaml, PowerShell/ScubaGear/Modules/ScubaConfig/ScubaConfig.psm1, Testing/workflow/Update-Opa.Tests.ps1, utils/workflow/Update-Opa.ps1
Moved code from workflow to a function.  Wrote unit tests for the function.
Closes: #1583 
To test the unit tests:
- Run workflow pipeline
- Check the workflow unit tests.  They should all pass.
To check functionality of the functions:
- Run "Update OPA executable version if necessary" workflow.  
- "Determine if update required" should tell you that it doesn't need to run, b/c branch already exists.
- Delete the branch.  https://github.com/cisagov/ScubaGear/branches/all?query=opa-version
- Run "Update OPA executable version if necessary" workflow.  
- "Determine if update required" should tell you that it needs to run now
- Look at "Create new PR".  It should have created a new PR.
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-rebas …
=> Add unit tests for update OPA version if necessary

Testing/Functional/Products/FunctionalTestUtils.ps1, Testing/Functional/Products/Products.Tests.ps1, Testing/Functional/Products/TestPlans/aad.g3.testplan.yaml, Testing/Functional/Products/TestPlans/aad.testplan.yaml, Testing/Functional/Products/TestPlans/defender.testplan.yaml, Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml, Testing/Functional/Products/TestPlans/sharepoint.pnp.testplan.yaml
The goal of this PR is to create improve on the functional test orchestrator, mainly making it so that instead of running ScubaGear each time when running ScubaCached, it instead only runs ScubaCached based on the previously existing RunScuba.
Closes #1010
There are a few things for reviewers to test:
1. Make sure the functional tests work on your system for all products including variants, and using service principles and interactive log in
2. Go through test plan changes, specifically the tests I changed from RunScuba to ScubaCached and if you disagree please let me know.
3. Use the Github Actions Functional Tests workflow and run it the PR branch, 1010-functional-test-improvements
Use `Rebase branch` button below or use [this](https://www.digitalocean.com/community/tutorials/how-to-reba …
=> Functional Test Improvements

PowerShell/ScubaGear/Modules/Connection/Connection.psm1, PowerShell/ScubaGear/Modules/Providers/ExportPowerPlatformProvider.psm1, PowerShell/ScubaGear/Rego/PowerPlatformConfig.rego, PowerShell/ScubaGear/Rego/Utils/KeyFunctions.rego, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/PowerPlatformProvider/Export-PowerPlatformProvider.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformBaseConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/PowerPlatform/PowerPlatformConfig_02_test.rego, Testing/Functional/Products/TestPlans/powerplatform.testplan.yaml
The Rego checks for POWERPLATFORM.2.1v1 and POWERPLATFORM2.2v1 were displaying incorrect results for certain conditions. The cause was due to a change in the underlying data structure which handles how DLP policies are applied to environments. 
Unit/functional tests were updated to reflect the new Rego updates.
Switched Get-TenantDetailsFromGraph commandlet to MS Graph's Get-MgBetaOrganization commandlet in the PowerPlatform provider due to the Azure AD Graph API deprecation.
Closes #1396
Closes #1686 
We've received a couple public reports of the PowerPlatform baseline failing due to a 403 forbidden status code from the Get-TenantDetailsFromGraph commandlet. The issue was pinpointed to the commandlet using Azure AD Graph endpoints, which will deprecated on June 30, 2025.
Run ScubaGear …
=> Fix PowerPlatform DLP policy bug and remove Get-TenantDetailsFromGraph commandlet

PowerShell/ScubaGear/Modules/Connection/Connection.psm1, PowerShell/ScubaGear/Modules/Orchestrator.psm1, PowerShell/ScubaGear/Modules/Permissions/ScubaGearPermissions.json, PowerShell/ScubaGear/Modules/Providers/ExportAADProvider.psm1, PowerShell/ScubaGear/Modules/Providers/ExportSharePointProvider.psm1, PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADRiskyPermissionsHelper.psm1, PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/CommandTracker.psm1, PowerShell/ScubaGear/RequiredVersions.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Connection/Connect-Tenant.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyApplications.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Format-RiskyThirdPartyServicePrincipals.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ApplicationsWithRiskyPermissions.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/AADRiskyPermissionsHelper/Get-ServicePrincipalsWithRiskyPermissions.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Get-AADTenantDetail.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/Invoke-GraphDirectly.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Providers/AADProvider/LoadObjectDataIntoPrivilegedUserHashtable.Tests.ps1, utils/UninstallModules.ps1
Removed the remaining three Microsoft Graph modules and converted those to API calls.
Microsoft.Graph.Beta.Applications
Microsoft.Graph.Beta.Identity.DirectoryManagement
Microsoft.Graph.Beta.DirectoryObjects
Closes #1595 
This will improve the performance of ScubaGear and reduce reliance on certain Microsoft Graph modules.
=> Remove dependency of remaining Microsoft Graph modules

PowerShell/ScubaGear/baselines/aad.md
This PR addresses minor typographical errors throughout the `aad.md` baseline document. The changes include:
- Updates made to reflect changes in the Entra portal UI since the last update.
- No changes to policy content, technical instructions, or guidance.
These edits are limited to typo fixes and do not alter the meaning or intent of any section.
- Provide clarification in the implementation steps for users that are not familiar with navigating the Entra portal.
- Closes #1736 
Manual testing to ensure the implementation steps are accurate against the Entra Portal UI
(Note: Only required for issues of size …
=> Update AAD baselines to reflect Entra Portal changes

PowerShell/ScubaGear/Modules/CreateReport/scripts/main.js, PowerShell/ScubaGear/Modules/CreateReport/styles/main.css, PowerShell/ScubaGear/Modules/Providers/ProviderHelpers/AADConditionalAccessHelper.psm1
Fixes the bug that caused AAD to fail when the tenant had no conditional access policies.
Closes #1756.
Closes #1748.
I first replicated the error by testing in a tenant with no CAPs. After fixing, tested again with no CAPs, with 1 CAP, and with multiple CAPs, all worked as expected.
=> Fix bug when tenant has no conditional access policies

PowerShell/ScubaGear/Rego/AADConfig.rego, PowerShell/ScubaGear/Testing/Unit/Rego/AAD/AADConfig_03_test.rego, PowerShell/ScubaGear/baselines/aad.md, Testing/Functional/Products/TestPlans/aad.testplan.yaml
Added additional values to account for tenants that are unable to migrate due to having newer tenants. Newer tenants will have null listed within the `ScubaResults_*****.json` file instead of `migrationComplete`.
Closes #1730
Run a scan of a test tenant. If the tenant doesn't have null listed within the results file, edit the file then run Invoke-SCuBACached to verify it passes.
```json
"authentication_method_policy":  {
"AuthenticationMethodConfigurations@odata.context":  "https://graph.microsoft.com/beta/$metadata#policies/authenticationMethodsPolicy/authenticationMethodConfigurations",
"PolicyVersion":  "1.5",
"PolicyMigrationState":  null,
"DisplayName":  "Authentication Methods Policy",
```
Use `Rebase branch` button below or use …
=> Update policy migration state (AAD 3.4)

Testing/Functional/Products/TestPlans/teams.testplan.yaml
Updated the functional test to reflect the correct version for MS.TEAMS.1.5 as v1 instead of V2
Functional Tests failing
Updated the version for functional tests. 
Closes #1788
=> Update test plan from MS.TEAMS.1.5v2 to MS.TEAMS.1.5v1 to fix Teams functional test failures.

PowerShell/ScubaGear/Modules/Support/Support.psm1, PowerShell/ScubaGear/ScubaGear.psd1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Reset-ScubaGearDependencies.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Test-ScubaGearVersion.Tests.ps1, PowerShell/ScubaGear/Testing/Unit/PowerShell/Support/Update-ScubaGear.tests.ps1, README.md, docs/installation/update.md
Added new functions in the support module to assist ScubaGear users with updating ScubaGear to newer versions and dependencies.
The existing upgrade documentation was minimal and didn't provide users with clear guidance on how to upgrade ScubaGear or understand their current installation status.
Created several functions to assist with updating and covered their functionality in the `upgrade.md` file.
closes #1223 
Test the newly added functions in the support module to verify options work as expected and the markdown and easy to understand.
=> Create update Instructions

PowerShell/ScubaGear/RequiredVersions.ps1
Added IsPinned to all modules listed in the RequiredVersions.ps1 File and set Graph to True.
Issues with later versions of Graph powershell. 
closes #1831 
=> Update RequiredVersions.ps1 with IsPinned values
